import {ThemeHero,ThemeFAQ} from '@/components/theme-sections';
import {AnimatedHeading} from '@/components/animated-heading';
import {GrowthPaths} from '@/components/growth-paths';
import { DivisionCards } from '@/components/divisions';
import { Breadcrumb, CTA, SectionTitle } from '@/components/blocks';
import { ServiceDirectory } from '@/components/service-directory';
import { pageMeta } from '@/lib/site';
export const metadata=pageMeta('Digital Marketing Services | SEO, Paid Ads & Conversion','Explore connected digital marketing services: SEO, Google Ads, Meta Ads, social media, landing pages and analytics. Request a scope built around your business.','/services');
export default function Services(){return <main id="main" className="theme-interior-page"><ThemeHero title={<>Digital Marketing Services<br/><span>for Business Growth</span></>} trail={[{label:'Services'}]} kicker={<>Choose the work you need</>} description={<>Digital Marketing Bureau (DMB) connects SEO services, Google Ads management, paid social advertising, lead generation and conversion rate optimisation. Choose the service that addresses your current problem, then review its deliverables and next step.</>}/><section className="section directory-section theme-project-services"><div className="theme-project-heading"><SectionTitle kicker="Our services" title="Choose the marketing work that moves your business forward."/><a className="button" href="/contact">Build my service plan</a></div><ServiceDirectory/></section><section className="section"><SectionTitle kicker="Connected expertise" title="Explore our service divisions."/><DivisionCards/></section><ThemeFAQ items={[{q:"Which marketing service should I start with?",a:"Start with the problem you want to solve: visibility, lead quality, advertising performance or conversions. Use the relevant audit option or share your goals so we can recommend a focused scope."},{q:"Can I combine SEO, paid ads and social media?",a:"Yes. We can agree a connected plan with clear responsibilities, deliverables and reporting for each channel."},{q:"Is an audit included on service pages?",a:"Each service page links to the relevant audit workflow. Public website checks and connected advertising account reviews require different data and access."},{q:"How do I know the scope and cost?",a:"We explain the recommended tasks, access, fee and timeline before work begins. Sending an inquiry does not commit you to buying."}]}/><CTA/></main>}
