import { validatePublicUrl,isPublicAddress } from '@/lib/audit';
import {expertReport} from '@/lib/audit-expert';
const headers={'Cache-Control':'private, no-store'};
async function checkDns(host:string,signal:AbortSignal){const answers=await Promise.all(['A','AAAA'].map(async type=>{const r=await fetch('https://cloudflare-dns.com/dns-query?name='+encodeURIComponent(host)+'&type='+type,{headers:{Accept:'application/dns-json'},signal});if(!r.ok)throw Error('The website domain could not be checked. Try again shortly.');const data=await r.json() as {Answer?:{type:number;data:string}[]};return (data.Answer||[]).filter(a=>a.type===1||a.type===28).map(a=>a.data)}));const addresses=answers.flat();if(!addresses.length||addresses.some(ip=>!isPublicAddress(ip)))throw Error('Only publicly reachable website domains can be audited.');}

async function discoveryFile(target:URL,signal:AbortSignal){try{await checkDns(target.hostname,signal);const r=await fetch(target,{redirect:'manual',signal,headers:{'User-Agent':'DMB-Website-Audit/2.0','Accept':'text/plain,application/xml,text/xml'}});if(!r.ok){await r.body?.cancel();return {status:r.status,body:''}}const reader=r.body?.getReader();if(!reader)return {status:r.status,body:''};let body='',size=0;const decoder=new TextDecoder();for(;;){const next=await reader.read();if(next.done)break;size+=next.value.length;if(size>100000){await reader.cancel();break}body+=decoder.decode(next.value,{stream:true})}body+=decoder.decode();return {status:r.status,body}}catch{return {status:null,body:''}}}

export async function POST(request:Request){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return Response.json({error:'Please use the audit form on the DMB website.'},{status:403,headers});try{const raw=await request.text();if(raw.length>2500)return Response.json({error:'Website address is too long.'},{status:400,headers});const data=JSON.parse(raw) as {url?:unknown};if(!data||typeof data!=='object'||typeof data.url!=='string'||data.url.length>2000)return Response.json({error:'Enter your website address.'},{status:400,headers});let url:URL;try{url=validatePublicUrl(data.url.trim())}catch(e){return Response.json({error:(e as Error).message},{status:400,headers})}
 const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),18000);try{let response:Response|undefined;for(let redirect=0;redirect<=3;redirect++){await checkDns(url.hostname,controller.signal);response=await fetch(url.toString(),{redirect:'manual',signal:controller.signal,headers:{'User-Agent':'DMB-Website-Audit/1.0','Accept':'text/html,application/xhtml+xml'}});if([301,302,303,307,308].includes(response.status)){const location=response.headers.get('location');if(!location||redirect===3)throw Error('The website has too many redirects. Try its final page URL.');await response.body?.cancel();url=validatePublicUrl(new URL(location,url).toString());continue}break}if(!response||!response.ok)throw Error('This page could not be accessed (HTTP '+(response?.status||'unknown')+'). It may block automated checks or require login.');if(!/text\/html|application\/xhtml\+xml/i.test(response.headers.get('content-type')||''))throw Error('Please submit an HTML webpage, not a file or API address.');const reader=response.body?.getReader();if(!reader)throw Error('The website returned no readable content.');const chunks:Uint8Array[]=[];let size=0;for(;;){const next=await reader.read();if(next.done)break;size+=next.value.length;if(size>1500000){await reader.cancel();throw Error('This page is too large for the quick audit. Try a smaller service page.')}chunks.push(next.value)}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length}const discoverySignal=AbortSignal.timeout(5000);const [robots,llms]=await Promise.all([discoveryFile(new URL('/robots.txt',url),discoverySignal),discoveryFile(new URL('/llms.txt',url),discoverySignal)]);let sitemapUrl=new URL('/sitemap.xml',url);const declared=robots.body.match(/^\s*Sitemap:\s*(\S+)/im)?.[1];if(declared){try{const candidate=validatePublicUrl(declared);if(candidate.origin===url.origin)sitemapUrl=candidate}catch{}}const sitemap=await discoveryFile(sitemapUrl,AbortSignal.timeout(5000));return Response.json({...expertReport(new TextDecoder().decode(bytes),url.toString(),response.headers,{robots:{...robots,url:new URL('/robots.txt',url).href},sitemap:{...sitemap,url:sitemapUrl.href},llms:{...llms,url:new URL('/llms.txt',url).href}}),checkedAt:new Date().toISOString()},{headers});}finally{clearTimeout(timer)}
 }catch(e){const err=e as Error;return Response.json({error:err.name==='AbortError'?'The website took too long to respond. Please try again or submit a different page.':err instanceof SyntaxError?'Enter a valid website address.':err.message||'The audit could not finish. Try again shortly.'},{status:422,headers});}}
