import {AnimatedHeading} from '@/components/animated-heading';
import {ServiceVisual} from '@/components/service-visual';
import {photoUrl} from '@/lib/photo-assets';
import Link from '@/components/navigation-link';
import {ArrowUpRight,ArrowRight} from 'lucide-react';
import {articles} from '@/lib/articles';
import {Breadcrumb,CTA} from '@/components/blocks';
import {pageMeta} from '@/lib/site';
export const metadata=pageMeta('Digital Marketing Blog | Practical Advice for Your Business','Explore practical DMB articles about online ads, website enquiries, useful leads and international marketing. Clear answers to common business problems.','/blog');
function photo(slug:string){return slug.includes('clicks')?'reach-right-customers':slug.includes('traffic')?'turn-visits-into-enquiries':slug.includes('qualified')?'understand-marketing-results':'find-your-business'}
export default function Blog(){const featured=articles[0];return <main id="main"><section className="page-intro blog-intro"><Breadcrumb items={[{label:'Blog'}]}/><span className="eyebrow">The DMB Blog</span><AnimatedHeading>Digital Marketing Blog:<br/><span>SEO, Ads & Lead Generation</span></AnimatedHeading><p>Practical answers about SEO, ads and business enquiries.</p></section><section className="section blog-content"><Link className="blog-feature" href={'/blog/'+featured.slug}><ServiceVisual slug="google-ads-management" featureKey="blog"/><div><span className="eyebrow">Start here / {featured.category}</span><h2>{featured.title}</h2><p>{featured.summary}</p><span className="blog-read">{featured.read} read · DMB Editorial</span><span className="text-link">Read the article <ArrowUpRight size={20}/></span></div></Link><div className="blog-grid-title"><h2>Explore more ideas.</h2><p>Useful answers to everyday marketing problems.</p></div><div className="blog-grid">{articles.slice(1).map(a=><Link className="blog-card" key={a.slug} href={'/blog/'+a.slug}><ServiceVisual featureKey={'guide-card-'+a.slug} slug={a.slug.includes('traffic')?'conversion-optimization':a.slug.includes('qualified')?'conversion-optimization':'seo-bureau'} compact/><div><span className="eyebrow">{a.category}</span><h3>{a.title}</h3><p>{a.summary}</p><span className="blog-read">{a.read} read</span><span className="text-link">Read article <ArrowRight size={18}/></span></div></Link>)}</div></section><CTA title="Need help with a problem you have read about?"/></main>}
