import {ServiceVisual} from '@/components/service-visual';
import Link from '@/components/navigation-link';
import { notFound } from 'next/navigation';
import { articles } from '@/lib/articles';
import { services } from '@/lib/content';
import { Breadcrumb, CTA, SectionTitle, ServiceCard, Schema } from '@/components/blocks';
import { pageMeta, origin } from '@/lib/site';
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(a=>a.slug===slug);return a?pageMeta(({ 'clicks-but-no-leads':'Google Ads Clicks but No Leads: What to Check','traffic-but-no-enquiries':'Website Traffic but No Enquiries: Conversion Guide','measure-qualified-leads':'How to Measure Lead Quality','international-service-pages':'International SEO for Service Businesses'} as Record<string,string>)[a.slug]||a.title,a.summary,'/resources/'+slug):{title:'Insight not found'}}
export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(a=>a.slug===slug);if(!a)notFound();return <main id="main"><section className="page-intro article-intro"><Breadcrumb items={[{label:'Guides',href:'/resources'},{label:a.category}]}/><span className="eyebrow">{a.category} / {a.read} read</span><h1>{a.title}</h1><p>{a.summary}</p><div className="article-byline"><Link href="/about">Digital Marketing Bureau editorial team</Link> · Updated 7 October 2026</div><div className="article-image"><ServiceVisual slug={slug.includes("clicks")?"google-ads-audit":slug.includes("traffic")?"conversion-rate-audit":slug.includes("qualified")?"lead-quality-optimization":"content-strategy"}/></div></section><article className="article-body">{a.sections.map((s,n)=><section key={s.title}><span className="eyebrow">0{n+1}</span><h2>{s.title}</h2><p>{s.body}</p></section>)}<div className="source-box"><span className="eyebrow">Further reading</span><a href={a.source.url} target="_blank" rel="noopener noreferrer">{a.source.label} ↗</a></div></article><section className="section related-section"><SectionTitle kicker="Turn the diagnosis into action" title="Explore the relevant services."/><div className="service-grid">{a.related.map(sl=>services.find(s=>s.slug===sl)).map(s=><ServiceCard service={s!} key={s!.slug}/>)}</div></section><CTA/><Schema data={{'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.summary,mainEntityOfPage:origin+'/resources/'+slug,author:{'@type':'Organization',name:'Digital Marketing Bureau'},publisher:{'@id':origin+'/#organization'},dateModified:'2026-10-07',about:a.category}}/></main>}
