import {env} from 'cloudflare:workers';
import {POST as websiteAudit} from '../route';
import {socialProfile,type SocialProfile} from '@/lib/social-discovery';
const headers={'Cache-Control':'private, no-store'};
const config=()=>env as unknown as {AUDIT_EXTERNAL_LOOKUPS?:string;SEARCHAPI_API_KEY?:string};
export async function GET(){const c=config();return Response.json({brandSearchConnected:c.AUDIT_EXTERNAL_LOOKUPS==='enabled'&&!!c.SEARCHAPI_API_KEY},{headers})}
export async function POST(request:Request){if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Use the DMB tool.'},{status:403,headers});try{const raw=await request.text();if(raw.length>2500)throw Error('Input is too long.');const data=JSON.parse(raw);const query=typeof data.query==='string'?data.query.trim():'';if(query.length<2||query.length>2000)throw Error('Enter a brand name, website or public social profile link.');const direct=socialProfile(query,'Supplied profile link');if(direct)return Response.json({profiles:[direct],message:'Profile link recognized. Add the brand website to discover its other linked profiles; a username alone does not prove accounts on other platforms belong to the same business.',complete:false},{headers});
 if(/^(?:https?:\/\/|\/\/|(?:www\.)?[a-z0-9-]+(?:\.[a-z0-9-]+)+(?::|\/|$))/i.test(query)&&!query.includes(' ')){const response=await websiteAudit(new Request(new URL('/api/audit',request.url),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:query})}));const report=await response.json() as any;if(!response.ok)return Response.json({error:report.error||'Could not read this website.'},{status:response.status,headers});return Response.json({profiles:report.socialProfiles||[],website:report.url,brand:report.business?.name,message:'Profiles found in the returned website links and structured data. Confirm they belong to your brand. Unlinked or JavaScript-only profiles may be missing.',complete:false},{headers})}
 const c=config();if(c.AUDIT_EXTERNAL_LOOKUPS!=='enabled'||!c.SEARCHAPI_API_KEY)return Response.json({error:'Brand-name search is not connected yet. Enter your website to discover its public social links, or paste a profile URL.',code:'BRAND_SEARCH_NOT_CONNECTED'},{status:503,headers});
 const profiles:SocialProfile[]=[];const groups=['(site:instagram.com OR site:facebook.com OR site:youtube.com OR site:linkedin.com)','(site:x.com OR site:twitter.com OR site:tiktok.com OR site:pinterest.com OR site:threads.net)'];await Promise.all(groups.map(async group=>{const u=new URL('https://www.searchapi.io/api/v1/search');u.searchParams.set('engine','google');u.searchParams.set('q','"'+query.slice(0,150).replace(/"/g,'')+'" '+group);const r=await fetch(u,{headers:{Authorization:'Bearer '+c.SEARCHAPI_API_KEY},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Brand search could not finish. Try the website link.');const result=await r.json() as any;if(!Array.isArray(result.organic_results))throw Error('Brand search returned no usable data.');for(const x of result.organic_results){const p=socialProfile(String(x.link||''),'Search result — confirm brand identity');if(p&&!profiles.some(v=>v.url===p.url))profiles.push({...p,title:String(x.title||'').slice(0,200)})}}));return Response.json({profiles:profiles.slice(0,25),message:'Public search candidates. Select only the profiles that belong to your brand. This search cannot prove that every platform account has been found.',complete:false},{headers})
 }catch(e){return Response.json({error:(e as Error).message||'Discovery could not finish.'},{status:400,headers})}}
