import settings from '@/content/settings.json';
import type { Metadata } from 'next';
import './globals.css';
import { Header, Footer } from '@/components/site-shell';
import { Schema } from '@/components/blocks';
import {PageMotion} from '@/components/page-motion';
import { MotionLayer } from '@/components/motion-layer';
import { origin } from '@/lib/site';
export const metadata: Metadata={metadataBase:new URL(origin),title:{default:'Digital Marketing Bureau | SEO & Performance Marketing',template:'%s | Digital Marketing Bureau'},description:'India-based SEO and performance marketing agency serving businesses worldwide. Google Ads, Meta Ads, organic marketing and websites built around useful enquiries.',alternates:{canonical:origin},openGraph:{title:'Digital Marketing Bureau | SEO, Ads & Social Media',description:'India-based digital marketing agency with remote delivery across markets.',images:[{url:'/social-preview.png',width:1200,height:630,alt:'Digital Marketing Bureau'}]},twitter:{card:'summary_large_image',images:['/social-preview.png']},icons:{icon:[{url:'/favicon.ico',type:'image/x-icon',sizes:'96x96'},{url:'/favicon.png',type:'image/png',sizes:'96x96'},{url:'/favicon.svg?v=2',type:'image/svg+xml'}],apple:'/favicon.png'}};
export default function RootLayout({children}:{children:React.ReactNode}) {return <html lang="en"><head><meta name="google-site-verification" content="u32am2xDfflHYzCsTwlBLYSAfopK3-U4yGnuwr8FL14"/><link rel="preload" href="/fonts/manrope-latin.woff" as="font" type="font/woff" crossOrigin="anonymous"/></head><body><a className="skip-link" href="#main">Skip to content</a><Header/>{children}<Footer/><MotionLayer/><PageMotion/><Schema data={{'@context':'https://schema.org','@type':'WebSite','@id':origin+'/#website',url:origin,name:'Digital Marketing Bureau',inLanguage:'en',publisher:{'@id':origin+'/#organization'}}}/><Schema data={{'@context':'https://schema.org','@type':'Organization','@id':origin+'/#organization',name:'Digital Marketing Bureau',alternateName:'DMB',url:origin,description:'India-based performance marketing agency working with businesses across markets.',email:settings.email,telephone:settings.phone,logo:origin+'/dmb-logo.svg',founder:{'@type':'Person',name:'Parmjeet Singh'},areaServed:['India','United States','United Kingdom','United Arab Emirates','Kuwait'],sameAs:[settings.linkedin,settings.instagram,settings.facebook,settings.x]}}/></body></html>}

