import Link from '@/components/navigation-link';
import {EditorialImage,ServiceVisual} from '@/components/service-visual';
import settings from '@/content/settings.json';
import {ArrowRight,ArrowUpRight,Check} from 'lucide-react';
import {CTA,SectionTitle,Schema} from '@/components/blocks';
import {markets} from '@/lib/markets';
import {HeroAudit} from '@/components/hero-audit';
import {IndustryCarousel} from '@/components/industry-carousel';
import {pageMeta} from '@/lib/site';
export const metadata=pageMeta('Performance Marketing & SEO Agency | Digital Marketing Bureau','SEO, online advertising and social media marketing for businesses. Get a free website check and a practical plan for clearer customer enquiries.','/');
const goals=[
{title:'Help customers find my business',text:'SEO, local search and clear service pages.',href:'/seo-bureau'},
{title:'Get more from my advertising',text:'Google, Meta and LinkedIn ads with useful tracking.',href:'/ppc-bureau'},
{title:'Build a stronger social presence',text:'Useful content and profiles that explain your offer.',href:'/social-bureau'},
{title:'Turn website visits into enquiries',text:'Better pages, simpler forms and a clear next step.',href:'/services/landing-page-design'}];
const questions=[['Where should I start?','Use the free website check, or tell us what you want to improve. We’ll explain the next step.'],['Can I choose one service?','Yes. Choose SEO, ads, social media or website support. We agree the scope before starting.'],['How much does it cost?','The fee depends on your needs. We share the work, price and timeline before you decide.'],['Do you guarantee sales?','No. Sales also depend on your offer, market and follow-up. We report progress without promising guaranteed results.']];
export default function Home(){return <main id="main">
<section className="brew-hero"><div className="brew-hero-copy"><span className="eyebrow hero-kicker">Digital Marketing Bureau</span><h1>{settings.heroTitle}<br/><span>{settings.heroHighlight}</span></h1><p>{settings.heroDescription}</p><div className="hero-buttons audit-secondary"><Link className="button" href="#problems">Explore our services <ArrowRight size={18}/></Link><Link className="hero-service-link" href="/contact">Talk about your goals <ArrowUpRight size={18}/></Link></div><aside id="website-check" className="hero-audit-panel" aria-labelledby="hero-audit-heading"><span className="eyebrow">Start with your website</span><h2 id="hero-audit-heading">Find your next improvement.</h2><p>A free page check, with a clearer next step.</p><HeroAudit/><div className="hero-audit-note">No payment required.</div></aside></div></section>
<section className="section editorial-intro" data-reveal><div className="editorial-image"><EditorialImage name="home-plan" alt="Business planning with written notes and customer priorities"/><span className="editorial-image-label">A plan built around your business</span></div><div className="editorial-copy"><span className="eyebrow">Clarity before more marketing</span><h2>Help customers understand<br/>why they should choose you.</h2><p>We help the right people find your business, understand your services and contact you.</p><ul className="editorial-points">{['Understand your customers and current challenge','Choose the work that fits your business','Agree the scope, fee and timeline first'].map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul><Link className="text-link" href="/about">Meet Digital Marketing Bureau <ArrowRight size={18}/></Link></div></section>
<section className="section goal-section" id="problems" data-reveal><SectionTitle kicker="Choose your next priority" title="What would you like to improve?" href="/services" linkText="All services"/><div className="goal-editorial"><div className="goal-list">{goals.map((g,n)=><Link className="goal-row" key={g.href} href={g.href}><span className="goal-number">0{n+1}</span><div><h3>{g.title}</h3><p>{g.text}</p></div><ArrowUpRight size={23}/></Link>)}</div><figure className="service-photograph goal-image"><EditorialImage name="home-priority" alt="Website design and development on a desktop workspace"/><figcaption>Search, ads, social media and your website work together.</figcaption></figure></div></section>
<section className="section brew-industries" data-reveal><SectionTitle kicker="Your customers. Your market." title="Marketing built for your industry." href="/industries" linkText="All industries"/><IndustryCarousel/></section>
<section className="section process-section" data-reveal><SectionTitle kicker="How we work" title="A clear plan. Three steps."/><div className="editorial-steps">{[['Tell us what needs to change','Share your website, customers and current challenge.'],['Review a focused recommendation','Understand the work, fee and timeline before deciding.'],['Start with agreed priorities','Receive clear updates and review the available evidence.']].map(([title,text],n)=><div className="editorial-step" key={title}><span>0{n+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
<section className="insight-section section" data-reveal><SectionTitle kicker="The DMB blog" title="Useful answers to real marketing problems." href="/blog" linkText="Read the blog"/><div className="insight-grid">{[['/resources/clicks-but-no-leads','Advertising','Ad clicks, but no enquiries?'],['/resources/traffic-but-no-enquiries','Your website','Why visitors leave without contacting you'],['/resources/measure-qualified-leads','Measurement','How to recognise a useful enquiry']].map(([url,tag,title])=><Link href={url} className="insight-card" key={url}><ServiceVisual featureKey={'guide-card-'+url.split('/').pop()} slug={url.includes('clicks-but')?'google-ads-audit':url.includes('traffic-but')?'conversion-rate-audit':'lead-quality-optimization'} compact/><div className="insight-copy"><span className="eyebrow">{tag}</span><h3>{title}</h3><ArrowUpRight size={21}/></div></Link>)}</div></section>
<section className="section home-faq" data-reveal><SectionTitle kicker="Before you get started" title="A few useful answers."/><div className="faq-list">{questions.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<CTA/><Schema data={{'@context':'https://schema.org','@type':'FAQPage',mainEntity:questions.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}}/></main>}

