import {GoalExplorer} from '@/components/goal-explorer';
import Link from '@/components/navigation-link';
import {EditorialImage,ServiceVisual} from '@/components/service-visual';
import settings from '@/content/settings.json';
import {ArrowRight,ArrowUpRight,Check} from 'lucide-react';
import {CTA,SectionTitle,Schema} from '@/components/blocks';
import {markets} from '@/lib/markets';
import {HeroAudit} from '@/components/hero-audit';
import {IndustryCarousel} from '@/components/industry-carousel';
import {pageMeta} from '@/lib/site';
export const metadata=pageMeta('Performance Marketing Agency & SEO Services | Digital Marketing Bureau','DMB is an India-based performance marketing agency offering SEO services, Google Ads and landing page optimisation worldwide. Get a free website audit.','/');
const goals=[
{title:'Help customers find my business',text:'SEO, local search and clear service pages.',href:'/seo-bureau'},
{title:'Get more from my advertising',text:'Google, Meta and LinkedIn ads with useful tracking.',href:'/ppc-bureau'},
{title:'Build a stronger social presence',text:'Useful content and profiles that explain your offer.',href:'/social-bureau'},
{title:'Turn website visits into enquiries',text:'Better pages, simpler forms and a clear next step.',href:'/services/landing-page-design'}];
const questions=[['Where should I start?','Use the free website check, or tell us what you want to improve. We’ll explain the next step.'],['Can I choose one service?','Yes. Choose SEO services, Google Ads management, social media marketing or website conversion support. We agree the scope before starting and explain any tracking or website work needed to support it.'],['How much does it cost?','The fee depends on your goals, website and agreed work. We share the deliverables, price and timeline before you decide. Advertising spend and any required third-party tools are identified separately.'],['Do you guarantee sales?','No. Sales also depend on your offer, market and follow-up. We report progress without promising guaranteed results.']];
export default function Home(){return <main id="main">
<section className="brew-hero"><div className="brew-hero-copy"><h1>{settings.heroTitle}{' '}<span>{settings.heroHighlight}</span></h1><p>{settings.heroDescription}</p><div className="hero-buttons audit-secondary"><Link className="button" href="#problems">Explore our services <ArrowRight size={18}/></Link><Link className="hero-service-link" href="/contact">Talk about your goals <ArrowUpRight size={18}/></Link></div><aside id="website-check" className="hero-audit-panel" aria-labelledby="hero-audit-heading"><span className="eyebrow">Find what’s holding your website back</span><h2 id="hero-audit-heading">Free Website Audit Tool</h2><p>One URL. Clear findings. Your next priorities.</p><HeroAudit/><div className="hero-audit-note">No signup. No payment. Just your website URL.</div></aside></div></section>
<section className="section editorial-intro" data-reveal><div className="editorial-image"><EditorialImage name="home-plan" alt="Business planning with written notes and customer priorities"/><span className="editorial-image-label">A plan built around your business</span></div><div className="editorial-copy"><span className="eyebrow">Clarity before more marketing</span><h2>SEO and performance marketing<br/>built around your business.</h2><p>DMB stands for Digital Marketing Bureau, an India-based performance marketing agency serving businesses worldwide. We help the right people find your business, understand your services and contact you through <Link href="/seo-bureau">SEO services</Link>, <Link href="/services/google-ads-management">Google Ads management</Link>, <Link href="/social-bureau">social media marketing</Link> and <Link href="/services/conversion-rate-audit">conversion rate optimisation</Link>.</p><p>Before recommending a channel, we review your offer, audience, existing website and enquiry journey. That helps identify whether your next priority is search visibility, advertising efficiency or converting the visitors you already receive.</p><ul className="editorial-points">{['Understand your customers and current challenge','Choose the work that fits your business','Agree the scope, fee and timeline first'].map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul><Link className="text-link" href="/about">Meet Digital Marketing Bureau <ArrowRight size={18}/></Link></div></section>
<section className="section goal-section" id="problems" data-reveal><SectionTitle kicker="Choose your next priority" title="What would you like to improve?" href="/services" linkText="All services"/><GoalExplorer/></section>
<section className="section brew-industries" data-reveal><SectionTitle kicker="Your customers. Your market." title="Marketing built for your industry." href="/industries" linkText="All industries"/><IndustryCarousel/></section>
<section className="section process-section" data-reveal><SectionTitle kicker="How we work" title="A clear plan. Three steps."/><div className="editorial-steps">{[['Tell us your main challenge','Share your website, target customers and current challenge. We review your service pages, enquiry paths and available campaign data to identify where useful leads may be getting lost.'],['Review your marketing plan','Receive a proposed scope with priorities, deliverables, fee and timeline. Choose a focused SEO service, an advertising review or support across connected channels, based on what your business needs.'],['Start the agreed work','We implement the agreed improvements and share progress against the measures selected at the start. Where reliable tracking is available, we review enquiries and conversion quality alongside traffic and advertising performance.']].map(([title,text],n)=><div className="editorial-step" key={title}><span>0{n+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
<section className="insight-section section" data-reveal><SectionTitle kicker="The DMB blog" title="Useful answers to real marketing problems." href="/blog" linkText="Read the blog"/><div className="insight-grid">{[['/blog/clicks-but-no-leads','Advertising','Ad clicks, but no enquiries?'],['/blog/traffic-but-no-enquiries','Your website','Why visitors leave without contacting you'],['/blog/measure-qualified-leads','Measurement','How to recognise a useful enquiry']].map(([url,tag,title])=><Link href={url} className="insight-card" key={url}><ServiceVisual featureKey={'guide-card-'+url.split('/').pop()} slug={url.includes('clicks-but')?'google-ads-audit':url.includes('traffic-but')?'conversion-rate-audit':'lead-quality-optimization'} compact/><div className="insight-copy"><span className="eyebrow">{tag}</span><h3>{title}</h3><ArrowUpRight size={21}/></div></Link>)}</div></section>
<section className="section home-faq" data-reveal><SectionTitle kicker="Before you get started" title="Questions before you start."/><div className="faq-list">{questions.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<CTA/><Schema data={{'@context':'https://schema.org','@type':'FAQPage',mainEntity:questions.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}}/></main>}

