'use client';
import {useState,useRef} from 'react';
import {HeroAudit} from './hero-audit';
import {analyzeAdsExport,type AdPlatform} from '@/lib/ads-export';
import styles from './audit-tool-workspaces.module.css';
export function AdsAuditWorkspace(){
 const requestId=useRef(0);
 const [platform,setPlatform]=useState<AdPlatform>('google');const [report,setReport]=useState<ReturnType<typeof analyzeAdsExport>|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 async function upload(file:File|undefined){if(!file)return;const id=++requestId.current;setReport(null);setError('');setLoading(true);try{if(file.size>2*1024*1024)throw Error('Use a CSV export smaller than 2 MB.');const result=analyzeAdsExport(await file.text(),platform);if(id===requestId.current)setReport(result)}catch(e){if(id===requestId.current)setError((e as Error).message)}finally{if(id===requestId.current)setLoading(false)}}
 const format=(n:number|null)=>n===null?'Not supplied':n.toLocaleString('en-US',{maximumFractionDigits:2});
 return <><div className={styles.tabs} aria-label="Advertising platform">{(['google','meta','linkedin'] as const).map(p=><button key={p} aria-pressed={p===platform} onClick={()=>{requestId.current++;setLoading(false);setPlatform(p);setReport(null);setError('')}}>{p==='google'?'Google Ads':p==='meta'?'Meta Ads':'LinkedIn Ads'}</button>)}</div><HeroAudit key={platform} fullPage auditKind="ads"/><section className={styles.panel}><h2>Audit your campaign export</h2><p>For actual campaign figures, choose the platform above and upload its campaign CSV. Include campaign name and spend; clicks and conversions or results add more detail. Your file is processed in this browser.</p><label className={styles.upload}>Choose campaign CSV<input key={platform} type="file" accept=".csv,text/csv" disabled={loading} onChange={e=>upload(e.target.files?.[0])}/></label>{loading&&<p role="status">Analyzing campaign rows…</p>}{error&&<p className={styles.error} role="alert">{error}</p>}{report&&<div aria-live="polite"><h3>Your export findings</h3><p>Source: uploaded {report.platform} export · {report.rows} rows · Spend units: {report.currency||'as supplied in the export'}</p><div className={styles.metrics}>{[['Spend',report.spend],['Clicks',report.clicks],[report.resultLabel,report.results],['Cost per click',report.cpc],['Cost per reported result',report.costPerResult]].map(([label,n])=><div key={String(label)}><span>{label}</span><strong>{format(n as number|null)}</strong></div>)}</div><p>These figures summarize the supplied rows. They do not establish tracking accuracy, lead quality, attribution, targeting or ROAS.</p>{report.findings.length?<ul>{report.findings.map((f,i)=><li key={i}><strong>{f.name}</strong><p>{f.detail}</p></li>)}</ul>:<p>No zero-click or zero-result spending rows were found in the available metrics. A manual account review can still identify other issues.</p>}</div>}</section></>
}
