'use client';
import {useEffect,useState} from 'react';
import Link from '@/components/navigation-link';
import {PerformanceComparison} from '@/components/performance-comparison';
import {ArrowUpRight} from 'lucide-react';
import type {AdsEvidence} from '@/components/expert-audit-report';
import type {AuditCheck} from '@/lib/audit';
import type {PerformanceComparisonResult} from '@/lib/audit-performance';
import {auditChoices,recommendAuditServices} from '@/lib/audit-plan';
import type {BusinessSignals,BusinessLookup} from '@/lib/audit-business';
export function AuditExplorer({url,checks,businessSignals:identity,onPerformance,onAds}:{url:string;businessSignals:BusinessSignals;checks:AuditCheck[];onPerformance?:(result:PerformanceComparisonResult)=>void;onAds?:(result:AdsEvidence)=>void}){
 const [goal,setGoal]=useState('Get found on Google');const [speed,setSpeed]=useState<PerformanceComparisonResult>({});const [lookup,setLookup]=useState<BusinessLookup|null>(null);const [lookupError,setLookupError]=useState('');const [selected,setSelected]=useState<string[]>([]);const [notice,setNotice]=useState('');
 useEffect(()=>{onPerformance?.(speed)},[speed,onPerformance]);
 const recommended=recommendAuditServices(checks,goal,Object.values(speed).some(r=>(r.lab?.score??100)<50));
 useEffect(()=>{setSelected(recommendAuditServices(checks,'Get found on Google',false).map(r=>r.slug))},[checks]);
 useEffect(()=>{const controller=new AbortController();setLookup(null);setLookupError('');fetch('/api/audit/business',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,name:identity.name,address:identity.address}),signal:controller.signal}).then(async r=>{const data=await r.json() as BusinessLookup;if(!r.ok||!Array.isArray(data.ads))throw Error();setLookup(data)}).catch(e=>{if(e.name!=='AbortError')setLookupError('Business data could not be retrieved. Other audit results are still available.')});return()=>controller.abort()},[url,identity.name,identity.address]);
 useEffect(()=>{onAds?.({country:'All markets',search:identity.name,records:lookup?.ads||[],listing:lookup?.listing,business:identity,checkedAt:lookup?.checkedAt})},[lookup,identity,onAds]);
 function changeGoal(value:string){setGoal(value);setSelected(recommendAuditServices(checks,value,Object.values(speed).some(r=>(r.lab?.score??100)<50)).map(r=>r.slug));setNotice('Suggestions updated for your selected goal. You can add or remove any service.')}
 const enquiry='Website audit for '+url+'. My goal: '+goal+'. Selected help: '+selected.map(sl=>auditChoices.find(c=>c.slug===sl)?.name).join(', ')+'. Automated business report: '+(lookup?.ads.map(a=>a.source+': '+a.status).join('; ')||'External data unavailable');
 return <div className="audit-explorer"><div className="audit-section-heading"><span className="eyebrow">Your business overview</span><h3>Results, without the homework.</h3><p>Your website details and connected data sources are checked automatically. Missing data stays clearly labelled.</p></div>

 <PerformanceComparison url={url} onResult={setSpeed}/>
 <details className="audit-module"><summary><span>2. Traffic & backlinks</span><small>Data unavailable</small></summary><div><p>Verified traffic and backlink totals are not available from the website page alone. This report does not invent visitor counts or links.</p><p>These results will appear automatically when an analytics or SEO data source is connected.</p></div></details>
 <details className="audit-module" open><summary><span>3. Advertising activity</span><small>{lookup?'Lookup completed':lookupError?'Data unavailable':'Checking…'}</small></summary><div>{lookupError&&<p role="status">{lookupError}</p>}{!lookup&&!lookupError&&<p role="status">Checking connected ad-library sources…</p>}{lookup?.ads.map(a=><article className="audit-library" key={a.source}><h4>{a.source}</h4><strong>{a.status}</strong>{a.count!==null&&a.count!==undefined&&<p>{a.count} matching records in the returned sample</p>}{a.advertiser&&<p>Advertiser: {a.advertiser}</p>}{(a.from||a.to)&&<p>Recorded dates: {a.from||'Not supplied'} — {a.to||'Not supplied'}</p>}<p>{a.detail}</p>{a.evidenceUrl&&<a href={a.evidenceUrl} target="_blank" rel="noopener noreferrer">View source evidence <ArrowUpRight size={15}/></a>}</article>)}{lookup&&<p>Checked {new Date(lookup.checkedAt).toLocaleString()}. Library records do not reveal ad spend, conversions or every sponsored search impression.</p>}</div></details>
 <details className="audit-module" open><summary><span>4. Your Google business listing</span><small>{lookup?.listing.status||'Checking…'}</small></summary><div><h4>Detected on your website</h4><dl><dt>Business</dt><dd>{identity.name}</dd><dt>Phone</dt><dd>{identity.phone||'Not declared in business structured data'}</dd><dt>Address</dt><dd>{identity.address||'Not declared in business structured data'}</dd></dl><p>{identity.source}. Website declarations are not independent verification of a Google listing.</p>{identity.mapsLinks.map(href=><p key={href}><a href={href} target="_blank" rel="noopener noreferrer">Maps link found on your website <ArrowUpRight size={15}/></a></p>)}<h4>Google Maps results</h4><p>{lookup?.listing.message||lookupError||'Checking connected listing source…'}</p>{lookup?.listing.matches.map((p,i)=><article className="audit-library" key={i}><h4>{p.name}</h4><p>{p.address}</p><p>{p.phone}</p><p>{p.rating===null?'Rating not supplied':p.rating+' / 5'} · {p.reviews===null?'Review count not supplied':p.reviews+' reviews'}</p>{p.hours.map(h=><p key={h}>{h}</p>)}<a href={p.mapsUrl} target="_blank" rel="noopener noreferrer">View on Google Maps <ArrowUpRight size={15}/></a><small>Google Maps</small></article>)}<p>Listing views, calls and clicks need the business owner’s authorised GBP connection.</p></div></details>
 <section className="audit-custom-plan"><span className="eyebrow">Choose what you want help with</span><h3>Your suggested starting plan.</h3><label>My main goal<select value={goal} onChange={e=>changeGoal(e.target.value)}>{[...new Set(auditChoices.map(c=>c.goal))].map(g=><option key={g}>{g}</option>)}</select></label><div className="audit-reasons">{recommended.length?recommended.map(r=><p key={r.slug}><strong>{auditChoices.find(c=>c.slug===r.slug)?.name}:</strong> {r.reason}</p>):<p>No automatic fixes were suggested from the basic checks. You can still choose help below.</p>}</div><button type="button" onClick={()=>{setSelected(recommended.map(r=>r.slug));setNotice('Suggested services selected. You can still change any choice.')}}>Use suggested services</button><fieldset><legend>Add or remove services</legend>{auditChoices.map(c=><label className="audit-tick" key={c.slug}><input type="checkbox" checked={selected.includes(c.slug)} onChange={e=>setSelected(e.target.checked?[...selected,c.slug]:selected.filter(s=>s!==c.slug))}/><span>{c.name} <Link href={'/services/'+c.slug}>Read about this service ↗</Link></span></label>)}</fieldset><p role="status">{notice||'This is a starting suggestion, not a complete diagnosis or a quote.'}</p><div className="audit-tool-actions"><Link className="button" href={'/contact?website='+encodeURIComponent(url)+'&service='+encodeURIComponent(selected[0]||'')+'&problem='+encodeURIComponent(enquiry)}>Ask for a customised plan <ArrowUpRight size={17}/></Link></div><p>We agree the work, price and timing before you decide. No payment is taken here.</p></section></div>
}

