import {AnimatedHeading} from '@/components/animated-heading';
import {Breadcrumb,Schema} from '@/components/blocks';
import {HeroAudit} from '@/components/hero-audit';
import {AdsAuditWorkspace} from '@/components/ads-audit-workspace';
import {SocialAuditWorkspace} from '@/components/social-audit-workspace';
import {auditTools,type AuditKind} from '@/lib/audit-tools';
import {origin} from '@/lib/site';
import shell from '@/app/dmb-audit/audit.module.css';
import styles from './audit-tool-page.module.css';
export function AuditToolPage({kind}:{kind:Exclude<AuditKind,'all'>}){const tool=auditTools.find(t=>t.kind===kind)!;return <main id="main" className={shell.workspace}><section className={shell.tool}><Breadcrumb items={[{label:'Audit tools',href:'/tools'},{label:tool.name}]}/><div className={styles.intro}><span>FREE ONLINE AUDIT</span><AnimatedHeading>{tool.title}</AnimatedHeading><p>{tool.description}</p></div>{kind==='ads'?<AdsAuditWorkspace/>:kind==='social'?<SocialAuditWorkspace/>:<HeroAudit fullPage auditKind="seo"/>}<details className={shell.coverage}><summary>What this tool can verify</summary><p>{kind==='seo'?'The website scan checks returned public HTML, metadata, schema and discovery files. Mobile and desktop performance run separately. Rankings, backlinks and search volumes are not measured.':kind==='ads'?'Website checks review the ad destination and visible tracking markers. CSV analysis summarizes the campaign rows you upload. It does not connect to your account or establish attribution, ROAS, conversion accuracy or targeting settings.':"Profile optimization checks compare the URL and copy you supply. The website scan discovers public profile links and sharing signals. Live profile content, ownership, followers, engagement and private account insights are not verified."}</p><p>Online findings are free to view. Paid report downloads remain unavailable until checkout is configured.</p></details></section><Schema data={{'@context':'https://schema.org','@type':'WebApplication',name:tool.name,url:origin+'/tools/'+tool.slug,applicationCategory:'BusinessApplication',operatingSystem:'Web browser',description:tool.meta,offers:{'@type':'Offer',price:0,priceCurrency:'USD'},publisher:{'@id':origin+'/#organization'}}}/></main>}
