import {ThemeHero} from '@/components/theme-sections';
import {LocalAuditWorkspace} from '@/components/local-audit-workspace';
import Link from '@/components/navigation-link';
import {AnimatedHeading} from '@/components/animated-heading';
import {Breadcrumb,Schema} from '@/components/blocks';
import {HeroAudit} from '@/components/hero-audit';
import {AdsAuditWorkspace} from '@/components/ads-audit-workspace';
import {SocialAuditWorkspace} from '@/components/social-audit-workspace';
import {auditTools,type AuditKind} from '@/lib/audit-tools';
import {origin} from '@/lib/site';
import shell from '@/app/dmb-audit/audit.module.css';
import styles from './audit-tool-page.module.css';
export function AuditToolPage({kind}:{kind:Exclude<AuditKind,'all'>}){const tool=auditTools.find(t=>t.kind===kind)!;return <main id="main" className={shell.workspace}><ThemeHero title={tool.title} kicker="FREE ONLINE AUDIT" description={tool.description} trail={[{label:"Audit tools",href:"/tools"},{label:tool.name}]}/><section className={shell.tool+" theme-audit-workbench"}><nav className={styles.toolNav} aria-label="Choose audit tool">{auditTools.map(t=><Link key={t.kind} href={t.href} aria-current={t.kind===kind?'page':undefined}>{t.name}</Link>)}</nav>{kind==='local'?<LocalAuditWorkspace/>:kind==='ads'?<AdsAuditWorkspace/>:kind==='social'?<SocialAuditWorkspace/>:<HeroAudit fullPage auditKind="seo"/>}<details className={shell.coverage}><summary>What this tool can verify</summary><p>{kind==='local'?'Business suggestions and listing details require the connected Google Places source. Local website scans are available separately. Ownership, private GBP insights and rankings are not established.':kind==='seo'?'The website scan checks returned public HTML, metadata, schema and discovery files. Mobile and desktop performance run separately. Rankings, backlinks and search volumes are not measured.':kind==='ads'?'Website checks review the ad destination and visible tracking markers. CSV analysis summarizes the campaign rows you upload. It does not connect to your account or establish attribution, ROAS, conversion accuracy or targeting settings.':"Website discovery finds public profile links; connected brand search returns candidates to confirm. Profile optimization checks compare the URL and copy you supply. Live profile content, ownership, followers, engagement and private account insights are not verified."}</p><p>Online findings are free to view. Paid report downloads remain unavailable until checkout is configured.</p></details></section><Schema data={{'@context':'https://schema.org','@type':'WebApplication',name:tool.name,url:origin+tool.href,applicationCategory:'BusinessApplication',operatingSystem:'Web browser',description:tool.meta,offers:{'@type':'Offer',price:0,priceCurrency:'USD'},publisher:{'@id':origin+'/#organization'}}}/></main>}

