'use client';
import {useEffect,useState} from 'react';
import Link from '@/components/navigation-link';
import {ArrowUpRight,LoaderCircle} from 'lucide-react';
import type {AdsEvidence} from '@/components/expert-audit-report';
import type {AuditCheck} from '@/lib/audit';
import type {PerformanceResult} from '@/lib/audit-performance';
import {auditChoices,recommendAuditServices} from '@/lib/audit-plan';
import type {BusinessSignals,BusinessLookup} from '@/lib/audit-business';
export function AuditExplorer({url,checks,businessSignals:identity,onPerformance,onAds}:{url:string;businessSignals:BusinessSignals;checks:AuditCheck[];onPerformance?:(result:PerformanceResult|null)=>void;onAds?:(result:AdsEvidence)=>void}){
 const [goal,setGoal]=useState('Get found on Google');const [speed,setSpeed]=useState<PerformanceResult|null>(null);const [busy,setBusy]=useState(false);const [speedError,setSpeedError]=useState('');const [lookup,setLookup]=useState<BusinessLookup|null>(null);const [lookupError,setLookupError]=useState('');const [selected,setSelected]=useState<string[]>([]);const [notice,setNotice]=useState('');
 useEffect(()=>{onPerformance?.(speed)},[speed,onPerformance]);
 const recommended=recommendAuditServices(checks,goal,(speed?.lab?.score??100)<50);
 useEffect(()=>{setSelected(recommendAuditServices(checks,'Get found on Google',false).map(r=>r.slug))},[checks]);
 useEffect(()=>{const controller=new AbortController();setBusy(true);fetch('/api/audit/performance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,strategy:'mobile'}),signal:controller.signal}).then(async r=>{const data=await r.json() as PerformanceResult&{error?:string};if(!r.ok)throw Error(data.error||'The speed check could not run.');setSpeed(data)}).catch(e=>{if(e.name!=='AbortError')setSpeedError('The speed check could not finish. Try again or open Google’s test below.')}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return()=>controller.abort()},[url]);
 async function testSpeed(strategy:'mobile'|'desktop'){setBusy(true);setSpeedError('');try{const r=await fetch('/api/audit/performance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,strategy}),signal:AbortSignal.timeout(65000)});const data=await r.json() as PerformanceResult&{error?:string};if(!r.ok)throw Error(data.error||'Speed check unavailable.');setSpeed(data)}catch{setSpeedError('The speed test could not finish. Please try Google’s test below.')}finally{setBusy(false)}}
 useEffect(()=>{const controller=new AbortController();setLookup(null);setLookupError('');fetch('/api/audit/business',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,name:identity.name,address:identity.address}),signal:controller.signal}).then(async r=>{const data=await r.json() as BusinessLookup;if(!r.ok||!Array.isArray(data.ads))throw Error();setLookup(data)}).catch(e=>{if(e.name!=='AbortError')setLookupError('Business data could not be retrieved. Other audit results are still available.')});return()=>controller.abort()},[url,identity.name,identity.address]);
 useEffect(()=>{onAds?.({country:'All markets',search:identity.name,records:lookup?.ads||[],listing:lookup?.listing,business:identity,checkedAt:lookup?.checkedAt})},[lookup,identity,onAds]);
 const format=(v:number|null,kind:string)=>v===null?'No data':kind==='cls'?v.toFixed(3):kind==='seconds'?(v/1000).toFixed(2)+' s':Math.round(v)+' ms';
 function changeGoal(value:string){setGoal(value);setSelected(recommendAuditServices(checks,value,(speed?.lab?.score??100)<50).map(r=>r.slug));setNotice('Suggestions updated for your selected goal. You can add or remove any service.')}
 const report=()=>({website:url,business:identity,goal,pageChecks:checks,performance:speed,externalData:lookup,externalDataError:lookupError||null,selectedServices:selected,generatedAt:new Date().toISOString()});
 function download(){const blob=new Blob([JSON.stringify(report(),null,2)],{type:'application/json'});const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download='dmb-audit-and-plan.json';a.click();URL.revokeObjectURL(href)}
 const enquiry='Website audit for '+url+'. My goal: '+goal+'. Selected help: '+selected.map(sl=>auditChoices.find(c=>c.slug===sl)?.name).join(', ')+'. Automated business report: '+(lookup?.ads.map(a=>a.source+': '+a.status).join('; ')||'External data unavailable');
 return <div className="audit-explorer"><div className="audit-section-heading"><span className="eyebrow">Your business overview</span><h3>Results, without the homework.</h3><p>Your website details and connected data sources are checked automatically. Missing data stays clearly labelled.</p></div>

 <details className="audit-module" open><summary><span>1. Loading speed & Core Web Vitals</span><small>{busy?'Checking…':speed?.status==='ready'?'Speed test returned':'Data may be unavailable'}</small></summary><div><p>Loading speed affects how easily people use your page. The mobile test starts automatically; you can also test desktop.</p><div className="audit-tool-actions"><button disabled={busy} onClick={()=>testSpeed('mobile')}>Test mobile</button><button disabled={busy} onClick={()=>testSpeed('desktop')}>Test desktop</button><a href={'https://pagespeed.web.dev/analysis?url='+encodeURIComponent(url)} target="_blank" rel="noopener noreferrer">Open Google PageSpeed <ArrowUpRight size={15}/></a></div>{busy&&<p role="status"><LoaderCircle size={15} className="audit-spinner"/> Google’s test can take about a minute. Other sections are ready to explore.</p>}{speedError&&<p role="alert">{speedError}</p>}{speed?.message&&<p>{speed.message}</p>}{speed?.lab&&<><h4>Google Lighthouse lab test · {speed.strategy}</h4>{speed.lab.categories&&<div className="audit-metric-grid">{Object.entries(speed.lab.categories).map(([name,value])=><div key={name}><strong>{value===null?'No data':value+'/100'}</strong><span>{name.replaceAll('-',' ')}</span></div>)}</div>}<div className="audit-metric-grid">{[['Performance',speed.lab.score===null?'No score':speed.lab.score+'/100'],['Main content loads (LCP)',format(speed.lab.lcp,'seconds')],['Layout movement (CLS)',format(speed.lab.cls,'cls')],['Blocked time (TBT)',format(speed.lab.tbt,'ms')]].map(([t,v])=><div key={t}><strong>{v}</strong><span>{t}</span></div>)}</div><p>This is a simulated test, not a Core Web Vitals pass. TBT does not measure real-visitor INP.</p>{!!speed.lab.diagnostics?.length&&<details><summary>Google test recommendations</summary>{speed.lab.diagnostics.map((d,n)=><div key={n}><h4>{d.title}</h4><p>{d.detail}</p></div>)}</details>}</>}{speed?.field?.status==='ready'?<><h4>Real-visitor Core Web Vitals · {speed.field.scope==='origin'?'whole website origin':'this page'}</h4><p>75th-percentile values from Chrome UX Report, not visitor counts.</p><div className="audit-metric-grid">{[['Main content loads (LCP)',format(speed.field.lcp,'seconds')],['Response to actions (INP)',format(speed.field.inp,'ms')],['Layout movement (CLS)',format(speed.field.cls,'cls')]].map(([t,v])=><div key={t}><strong>{v}</strong><span>{t}</span></div>)}</div></>:<p><strong>Real-visitor Core Web Vitals:</strong> {speed?.field?.message||'Waiting for data availability. Missing data is not a pass or a fail.'}</p>}</div></details>
 <details className="audit-module"><summary><span>2. Traffic & backlinks</span><small>Data unavailable</small></summary><div><p>Verified traffic and backlink totals are not available from the website page alone. This report does not invent visitor counts or links.</p><p>These results will appear automatically when an analytics or SEO data source is connected.</p></div></details>
 <details className="audit-module" open><summary><span>3. Advertising activity</span><small>{lookup?'Lookup completed':lookupError?'Data unavailable':'Checking…'}</small></summary><div>{lookupError&&<p role="status">{lookupError}</p>}{!lookup&&!lookupError&&<p role="status">Checking connected ad-library sources…</p>}{lookup?.ads.map(a=><article className="audit-library" key={a.source}><h4>{a.source}</h4><strong>{a.status}</strong>{a.count!==null&&a.count!==undefined&&<p>{a.count} matching records in the returned sample</p>}{a.advertiser&&<p>Advertiser: {a.advertiser}</p>}{(a.from||a.to)&&<p>Recorded dates: {a.from||'Not supplied'} — {a.to||'Not supplied'}</p>}<p>{a.detail}</p>{a.evidenceUrl&&<a href={a.evidenceUrl} target="_blank" rel="noopener noreferrer">View source evidence <ArrowUpRight size={15}/></a>}</article>)}{lookup&&<p>Checked {new Date(lookup.checkedAt).toLocaleString()}. Library records do not reveal ad spend, conversions or every sponsored search impression.</p>}</div></details>
 <details className="audit-module" open><summary><span>4. Your Google business listing</span><small>{lookup?.listing.status||'Checking…'}</small></summary><div><h4>Detected on your website</h4><dl><dt>Business</dt><dd>{identity.name}</dd><dt>Phone</dt><dd>{identity.phone||'Not declared in business structured data'}</dd><dt>Address</dt><dd>{identity.address||'Not declared in business structured data'}</dd></dl><p>{identity.source}. Website declarations are not independent verification of a Google listing.</p>{identity.mapsLinks.map(href=><p key={href}><a href={href} target="_blank" rel="noopener noreferrer">Maps link found on your website <ArrowUpRight size={15}/></a></p>)}<h4>Google Maps results</h4><p>{lookup?.listing.message||lookupError||'Checking connected listing source…'}</p>{lookup?.listing.matches.map((p,i)=><article className="audit-library" key={i}><h4>{p.name}</h4><p>{p.address}</p><p>{p.phone}</p><p>{p.rating===null?'Rating not supplied':p.rating+' / 5'} · {p.reviews===null?'Review count not supplied':p.reviews+' reviews'}</p>{p.hours.map(h=><p key={h}>{h}</p>)}<a href={p.mapsUrl} target="_blank" rel="noopener noreferrer">View on Google Maps <ArrowUpRight size={15}/></a><small>Google Maps</small></article>)}<p>Listing views, calls and clicks need the business owner’s authorised GBP connection.</p></div></details>
 <section className="audit-custom-plan"><span className="eyebrow">Choose what you want help with</span><h3>Your suggested starting plan.</h3><label>My main goal<select value={goal} onChange={e=>changeGoal(e.target.value)}>{[...new Set(auditChoices.map(c=>c.goal))].map(g=><option key={g}>{g}</option>)}</select></label><div className="audit-reasons">{recommended.length?recommended.map(r=><p key={r.slug}><strong>{auditChoices.find(c=>c.slug===r.slug)?.name}:</strong> {r.reason}</p>):<p>No automatic fixes were suggested from the basic checks. You can still choose help below.</p>}</div><button type="button" onClick={()=>{setSelected(recommended.map(r=>r.slug));setNotice('Suggested services selected. You can still change any choice.')}}>Use suggested services</button><fieldset><legend>Add or remove services</legend>{auditChoices.map(c=><label className="audit-tick" key={c.slug}><input type="checkbox" checked={selected.includes(c.slug)} onChange={e=>setSelected(e.target.checked?[...selected,c.slug]:selected.filter(s=>s!==c.slug))}/><span>{c.name} <Link href={'/services/'+c.slug}>Read about this service ↗</Link></span></label>)}</fieldset><p role="status">{notice||'This is a starting suggestion, not a complete diagnosis or a quote.'}</p><div className="audit-tool-actions"><button onClick={download}>Download report & choices</button><Link className="button" href={'/contact?website='+encodeURIComponent(url)+'&service='+encodeURIComponent(selected[0]||'')+'&problem='+encodeURIComponent(enquiry)}>Ask for a customised plan <ArrowUpRight size={17}/></Link></div><p>We agree the work, price and timing before you decide. No payment is taken here.</p></section></div>
}
