 'use client';
import {useState} from 'react';
import type {ReactNode} from 'react';
type Source={url:string;title:string;start?:number;end?:number};
function CitedText({text,sources}:{text:string;sources:Source[]}){
 const pieces:ReactNode[]=[];let cursor=0;
 for(const [i,s] of [...sources].sort((a,b)=>(a.start??Infinity)-(b.start??Infinity)).entries()){
  if(typeof s.start!=='number'||typeof s.end!=='number'||s.start<cursor||s.end<=s.start||s.end>text.length)continue;
  pieces.push(text.slice(cursor,s.start),<a key={i} href={s.url} target="_blank" rel="noopener noreferrer" title={s.title}>{text.slice(s.start,s.end)}</a>);cursor=s.end;
 }
 pieces.push(text.slice(cursor));return <>{pieces}</>;
}
export function AuditAI({url}:{url:string}){
 const[country,setCountry]=useState('IN'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{blocks:{text:string;sources:Source[]}[];scope:string;checkedAt:string;provider?:string}|null>(null);
 async function research(){setBusy(true);setError('');setResult(null);try{const r=await fetch('/api/audit/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,country}),signal:AbortSignal.timeout(120000)});const data=await r.json() as {error?:string;blocks:{text:string;sources:Source[]}[];scope:string;checkedAt:string;provider?:string};if(!r.ok)throw Error(data.error||'Research unavailable.');setResult(data)}catch(e){setError((e as Error).name==='TimeoutError'?'Research took too long. Try again later.':(e as Error).message)}finally{setBusy(false)}}
 return <section className="audit-ai"><span className="eyebrow">AI / Evidence-led research</span><h3>Understand your priorities and competitors.</h3><p>Get a clear explanation of your page audit and up to three likely direct competitors in your target market.</p><div className="audit-ai-controls"><label>Target market<select value={country} onChange={e=>{setCountry(e.target.value);setResult(null)}} disabled={busy}><option value="IN">India</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="AE">UAE / Dubai</option><option value="KW">Kuwait</option></select></label><button className="button" onClick={research} disabled={busy}>{busy?'Researching your website…':'Generate free AI insights'}</button></div>{busy&&<p role="status">Checking page evidence and researching competitors. This can take about a minute.</p>}{error&&<p role="alert">{error}</p>}{result&&<div className="audit-ai-result">{result.blocks.map((b,n)=><div key={n}><p className="audit-ai-text"><CitedText text={b.text} sources={b.sources}/></p>{b.sources.length>0&&<ul>{b.sources.map((s,i)=><li key={i}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title} ↗</a></li>)}</ul>}</div>)}<p className="audit-limits">{result.provider&&`Research by ${result.provider}. `}{result.scope} Checked {new Date(result.checkedAt).toLocaleString()}.</p></div>}<div className="audit-paid-preview"><div><span className="eyebrow">Full audit / US$1 one-time</span><h4>A detailed optimisation plan for up to 20 pages.</h4><p>Planned: 10 competitor profiles, 1 primary and 2 secondary keyword suggestions per page, and priority recommendations.</p></div><p><strong>Checkout coming soon.</strong> Full reports will unlock after verified payment. Keyword rankings and volumes require a connected SEO data source.</p></div></section>
}
