'use client';
import {useState} from 'react';
import Link from '@/components/navigation-link';
import {AnimatedImage} from '@/components/animated-image';
import {ArrowUpRight,Check} from 'lucide-react';
const goals=[
{label:'Customers cannot find me',name:'on-page-seo',title:'Be visible when customers need you.',problem:'Your service is useful, but the right searches are not reaching your website.',steps:['Find the searches that match your offer','Improve the pages that answer those searches','Connect relevant pages to a clear enquiry action'],href:'/seo-bureau',cta:'Explore SEO services'},
{label:'Ad clicks are not turning into leads',name:'google-ads-management',title:'Give every click a clearer next step.',problem:'People click your ads, then leave. We look at targeting, search terms and the landing page together.',steps:['Review where the advertising budget goes','Match the message to customer intent','Remove friction from the enquiry journey'],href:'/services/google-ads-management',cta:'Explore an advertising audit'},
{label:'My social presence feels inconsistent',name:'social-media-strategy',title:'Show a brand people can recognise.',problem:'Your profiles and posts need a clear purpose, a consistent message and an easy route to contact you.',steps:['Clarify the audience and your offer','Plan useful content around real questions','Build a consistent profile and publishing approach'],href:'/smm-bureau',cta:'Explore social media services'},
{label:'Website visitors leave without enquiring',name:'conversion-optimization',title:'Help visitors feel ready to enquire.',problem:'A visitor should quickly understand your offer, find useful proof and know what happens next.',steps:['Review the visitor journey','Make the offer and contact action clear','Prioritise changes worth testing'],href:'/services/conversion-optimization',cta:'Explore conversion optimisation'}
];
export function GoalExplorer(){const [selected,setSelected]=useState(0);const goal=goals[selected];return <div className="goal-explorer"><div className="goal-choices" role="group" aria-label="Choose your marketing challenge">{goals.map((g,i)=><button type="button" key={g.name} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span className="goal-choice-text"><strong>{g.label}</strong><small>{i===0?'Improve search visibility and service pages.':i===1?'Review targeting, ad spend and landing pages.':i===2?'Build clear profiles and consistent content.':'Improve the offer and enquiry journey.'}</small></span></button>)}</div><div className="goal-preview" aria-live="polite"><div className="goal-preview-copy"><div className="goal-preview-thumbnail"><AnimatedImage name={selected===0?'goal-search-discovery':goal.name} compact/></div><span className="eyebrow">Your challenge. A practical direction.</span><h3>{goal.title}</h3><p>{goal.problem}</p><ul>{goal.steps.map(step=><li key={step}><Check size={17}/>{step}</li>)}</ul><Link className="text-link" href={goal.href}>{goal.cta}<ArrowUpRight size={18}/></Link></div></div></div>}
