import {ThemeHero} from '@/components/theme-sections';
import {AnimatedHeading} from '@/components/animated-heading';
import {IndustryTicker} from '@/components/industry-ticker';
import {ServiceVisual} from '@/components/service-visual';
import Link from '@/components/navigation-link';
import {ArrowUpRight} from 'lucide-react';
import {Breadcrumb,CTA,SectionTitle,ServiceCard,Schema} from '@/components/blocks';
import {services,industries} from '@/lib/content';
import {growthPaths} from '@/lib/growth-paths';
import {photoUrl} from '@/lib/photo-assets';
import {origin} from '@/lib/site';
export function GrowthServicePage({slug}:{slug:string}){const p=growthPaths.find(p=>p.slug===slug)!;return <main id="main" className="theme-interior-page"><ThemeHero title={<>{p.headline}</>} trail={[{label:'Services',href:'/services'},{label:p.name}]} kicker={<>{p.name} agency services</>} description={<>{p.intro}</>} visual={<ServiceVisual featureKey={slug} slug={slug==='organic-marketing'?'seo-bureau':'paid-media-strategy'} eager/>} actionContent={<Link className="button" href={'/contact?problem='+encodeURIComponent('I would like a '+p.name+' plan for my business.')}>Request my marketing plan <ArrowUpRight size={20}/></Link>}/><section className="section"><SectionTitle kicker="A connected approach" title="From customer interest to a useful enquiry."/><div className="theme-journey-grid">{p.steps.map(([title,text],n)=><div className="theme-journey-card" key={title}><span>0{n+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section><section className="section related-section"><SectionTitle kicker="Choose the work you need" title={'Explore our '+p.name+' services.'} text="Start with one priority or combine services in an agreed plan. Each page explains the work and what we need from you."/><div className="service-grid">{p.services.map(slug=>services.find(s=>s.slug===slug)!).map(s=><ServiceCard key={s.slug} service={s}/>)}</div></section><section className="section"><SectionTitle kicker="Your market and offer" title="Built around how your customers buy."/><IndustryTicker items={industries.map(({slug,name})=>({slug,name}))}/></section><section className="section"><SectionTitle kicker="Before you choose" title="Questions business owners ask."/><div className="faq-list theme-faq-list">{p.faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div><Link className="text-link" href={slug==='organic-marketing'?'/seo-bureau':'/organic-marketing'}>{slug==='organic-marketing'?'Explore SEO Bureau':'Explore organic marketing too'} <ArrowUpRight size={18}/></Link></section><CTA title="What should your business improve first?" text="Share your website, target market and current challenge. Request a focused plan with clear deliverables and fees."/><Schema data={{'@context':'https://schema.org','@type':'Service',name:p.name+' services',description:p.summary,url:origin+'/'+p.slug,provider:{'@id':origin+'/#organization'}}}/></main>}
