'use client';
import { createPortal } from 'react-dom';
import { useState, useEffect } from 'react';
import Link from '@/components/navigation-link';
import { ArrowUpRight, Check, CircleAlert, LoaderCircle, Search, X, ArrowRight } from 'lucide-react';
import { AuditExplorer } from '@/components/audit-explorer';
import type { AuditCheck } from '@/lib/audit';
type Result={url:string;title:string;checks:AuditCheck[];score:number;passed:number;total:number;checkedAt:string};
export function HeroAudit(){const [url,setUrl]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<Result|null>(null);useEffect(()=>{if(!result)return;const previousFocus=document.activeElement as HTMLElement|null;const handle=(e:KeyboardEvent)=>{if(e.key==='Escape')setResult(null);if(e.key==='Tab'){const nodes=Array.from(document.querySelectorAll<HTMLElement>('.audit-report button,.audit-report a,.audit-report input,.audit-report select,.audit-report summary')).filter(el=>!el.hasAttribute('disabled')&&el.getClientRects().length);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handle);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handle);document.body.style.overflow=previous;previousFocus?.focus()}},[result]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');try{const r=await fetch('/api/audit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:url.trim()}),signal:AbortSignal.timeout(25000)});const data=await r.json() as Result&{error?:string};if(!r.ok)throw Error(data.error||'The audit could not finish. Try again shortly.');if(!Array.isArray(data.checks))throw Error('The audit could not be confirmed. Try again.');setResult(data)}catch(e){const err=e as Error;setError(err.name==='TimeoutError'?'The website took too long to respond. Please try again.':err.message)}finally{setLoading(false)}}
return <div className="hero-audit"><form onSubmit={submit}><label htmlFor="hero-website">Your website address</label><div className="audit-input-row"><div className="audit-url-field"><Search size={18}/><input id="hero-website" type="text" inputMode="url" autoComplete="url" spellCheck={false} name="website" placeholder="Enter your website URL" required maxLength={2000} value={url} onChange={e=>setUrl(e.target.value)} disabled={loading}/></div><button className="button" disabled={loading} type="submit">{loading?<><LoaderCircle className="audit-spinner" size={17}/>Auditing…</>:<>Check my website<ArrowUpRight size={19}/></>}</button></div><p className="audit-helper">Checks one page. Optional speed tests and guided ads or local listing reviews are available in your report.</p>{loading&&<p className="audit-progress" role="status">Checking your page for missing information and basic website issues…</p>}{error&&<p className="audit-error" role="alert">{error}</p>}</form>{result&&createPortal(<div className="audit-overlay" onClick={e=>{if(e.target===e.currentTarget)setResult(null)}}><section className="audit-report" role="dialog" aria-modal="true" aria-labelledby="audit-report-title"><div className="audit-report-heading"><div><span className="eyebrow">DMB / Quick website audit</span><h2 id="audit-report-title">Here is what we found.</h2></div><button className="icon-btn" autoFocus aria-label="Close audit report" onClick={()=>setResult(null)}><X/></button></div><div className="audit-summary"><div className="audit-score"><strong>{result.passed}<span>/{result.total}</span></strong><span>checks passed</span></div><div><p className="audit-page-title">{result.title||'No page title found'}</p><a href={result.url} target="_blank" rel="noopener noreferrer">{result.url} ↗</a><p>Checked {new Date(result.checkedAt).toLocaleString()}</p></div></div><p className="audit-limits">These 11 checks examine the returned HTML of one page, not your full website. Explore speed, traffic, advertising and your business listing below. Each section explains its data source and limits.</p><div className="audit-checks">{result.checks.map(check=><details key={check.id} open={!check.passed}><summary><span className={check.passed?'check-pass':'check-review'}>{check.passed?<Check size={16}/>:<CircleAlert size={16}/>}</span><strong>{check.name}</strong><span>{check.passed?'Passed':'Review'}</span></summary><div><p>{check.detail}</p>{!check.passed&&<p className="audit-fix"><strong>Next step:</strong> {check.fix}</p>}</div></details>)}</div><AuditExplorer url={result.url} checks={result.checks}/></section></div>,document.body)}</div>}
