'use client';
import { createPortal } from 'react-dom';
import { useState, useEffect } from 'react';
import Link from '@/components/navigation-link';
import { ArrowUpRight, Check, CircleAlert, LoaderCircle, Search, X, ArrowRight } from 'lucide-react';
import {AuditAI} from '@/components/audit-ai';
import {SiteCrawlReport} from '@/components/site-crawl-report';
import { AuditExplorer } from '@/components/audit-explorer';
import type {ExpertResult,AdsEvidence} from '@/components/expert-audit-report';
import {MarketingAuditReport} from '@/components/marketing-audit-report';
import type {PerformanceComparisonResult} from '@/lib/audit-performance';
type Result=ExpertResult;
export function HeroAudit({fullPage=false}:{fullPage?:boolean}={}){const [url,setUrl]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<Result|null>(null);const [performance,setPerformance]=useState<PerformanceComparisonResult>({});const [ads,setAds]=useState<AdsEvidence|null>(null);useEffect(()=>{if(fullPage){const initial=new URLSearchParams(window.location.search).get('url');if(initial)setUrl(initial.slice(0,2000))}},[fullPage]);useEffect(()=>{if(!result||fullPage)return;const previousFocus=document.activeElement as HTMLElement|null;const handle=(e:KeyboardEvent)=>{if(e.key==='Escape')setResult(null);if(e.key==='Tab'){const nodes=Array.from(document.querySelectorAll<HTMLElement>('.audit-report button,.audit-report a,.audit-report input,.audit-report select,.audit-report summary')).filter(el=>!el.hasAttribute('disabled')&&el.getClientRects().length);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handle);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handle);document.body.style.overflow=previous;previousFocus?.focus()}},[result,fullPage]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');setResult(null);try{const r=await fetch('/api/audit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:url.trim()}),signal:AbortSignal.timeout(25000)});const data=await r.json() as Result&{error?:string};if(!r.ok)throw Error(data.error||'The audit could not finish. Try again shortly.');if(!Array.isArray(data.checks))throw Error('The audit could not be confirmed. Try again.');setPerformance({});setAds(null);setResult(data)}catch(e){const err=e as Error;setError(err.name==='TimeoutError'?'The website took too long to respond. Please try again.':err.message)}finally{setLoading(false)}}
return <div className={`hero-audit${result?' audit-has-result':''}`}><div className="audit-tool-chrome" aria-hidden="true"><div className="audit-tool-dots"><i/><i/><i/></div><span>dmb / marketing analyser</span><b>FREE</b></div><form onSubmit={submit}><label className="audit-tool-label" htmlFor="hero-website">Website URL to audit</label><div className="audit-input-row"><div className="audit-url-field"><Search size={18}/><input id="hero-website" type="text" inputMode="url" autoComplete="url" spellCheck={false} name="website" placeholder={fullPage?"example.com":"https://yourwebsite.com"} required maxLength={2000} value={url} onChange={e=>setUrl(e.target.value)} disabled={loading}/></div><button className="button" disabled={loading} type="submit">{loading?<><LoaderCircle className="audit-spinner" size={17}/>Auditing…</>:<>{fullPage?"Audit website":"Run Free Audit"}<ArrowRight size={19}/></>}</button></div><p className="audit-helper">{fullPage?"Enter your website URL to get a free marketing audit. No signup required.":"Check SEO, social links, advertising readiness and conversion signals."}</p>{loading&&<p className="audit-progress" role="status">Reading your website, marketing signals and discovery files…</p>}{error&&<p className="audit-error" role="alert">{error}</p>}</form><div className="audit-tool-capabilities"><span><Check size={14}/>SEO</span><span><Check size={14}/>Social media</span><span><Check size={14}/>Ads readiness</span></div>{result&&(fullPage?<section className="audit-full-report" aria-label="Your website marketing report"><MarketingAuditReport report={result} performance={performance} ads={ads}/><SiteCrawlReport url={result.url}/><AuditExplorer url={result.url} businessSignals={result.business} checks={result.checks} onPerformance={setPerformance} onAds={setAds}/><AuditAI url={result.url}/></section>:createPortal(<div className="audit-overlay" onClick={e=>{if(e.target===e.currentTarget)setResult(null)}}><section className="audit-report" role="dialog" aria-modal="true" aria-labelledby="audit-report-title"><div className="audit-report-heading"><div><span className="eyebrow">DMB / Marketing audit report</span><h2 id="audit-report-title">Your website report.</h2></div><button className="icon-btn" autoFocus aria-label="Close audit report" onClick={()=>setResult(null)}><X/></button></div><MarketingAuditReport report={result} performance={performance} ads={ads}/><SiteCrawlReport url={result.url}/><AuditExplorer url={result.url} businessSignals={result.business} checks={result.checks} onPerformance={setPerformance} onAds={setAds}/><AuditAI url={result.url}/></section></div>,document.body))}</div>}
