'use client';
import {photoUrl} from '@/lib/photo-assets';
import { industryPhoto,servicePhoto } from '@/lib/visuals';
import { useState } from 'react';
import Link from '@/components/navigation-link';
import { ArrowUpRight, ArrowRight, Check, Crosshair, Search, MousePointer2, ChartNoAxesCombined, Workflow } from 'lucide-react';
import { services, industries } from '@/lib/client-content';
const capabilities=[
 {key:'Paid media',label:'Advertise online',icon:Crosshair,headline:'Reach customers with a relevant offer.',description:'Online ads put your offer in front of potential customers. We help choose where to advertise, improve existing ads and review whether the enquiries are useful.',slugs:['google-ads-audit','google-ads-management','paid-social-advertising','linkedin-advertising'],outcomes:['Choose who sees your ads','Make your offer and next step clear','Review how your budget is used']},
 {key:'Organic growth',label:'Get found on Google',icon:Search,headline:'Match your services to buying-intent searches.',description:'Search engine optimisation (SEO) helps search engines understand your website. We improve useful pages, check website errors and help local customers find your business.',slugs:['technical-seo-audit','on-page-seo','local-seo','ai-search-visibility'],outcomes:['Explain your services clearly','Improve pages for relevant searches','Help visitors find related information']},
 {key:'Conversion',label:'Improve my website',icon:MousePointer2,headline:'Turn a useful visit into a clearer enquiry.',description:'Visitors should understand what you offer and how to contact you. We check confusing pages, improve forms and design focused pages for your ads.',slugs:['landing-page-design','conversion-rate-audit','lead-quality-optimization','website-speed-optimization'],outcomes:['Explain what you offer','Ask useful enquiry questions','Identify what needs improving']},
 {key:'Measurement',label:'Understand my results',icon:ChartNoAxesCombined,headline:'Understand where your enquiries come from.',description:'We set up tools to record important actions, such as form submissions, and create reports you can understand. This helps you review what your marketing is doing.',slugs:['conversion-tracking-setup','analytics-dashboards','google-ads-audit'],outcomes:['Agree which actions to record','See important numbers together','Use available data to review spending']},
 {key:'Pipeline',label:'Follow up enquiries',icon:Workflow,headline:'Keep useful enquiries moving.',description:'We help businesses find suitable prospects, send helpful follow-up emails and organise repeated tasks so enquiries reach the right people.',slugs:['b2b-lead-generation','email-lead-nurturing','marketing-automation'],outcomes:['Decide who you want to reach','Pass enquiries to the right person','Plan helpful follow-up messages']},
 {key:'Social media',label:'Plan my social posts',icon:Workflow,headline:'Build a social presence around real customer questions.',description:'Social Media Marketing (SMM) helps people understand your business through social platforms. We plan useful content, improve your profiles and help with regular posts.',slugs:['social-media-strategy','social-profile-setup','social-media-content-management'],outcomes:['Choose suitable social platforms','Explain your services clearly','Give people an easy way to contact you']}
];
export function CapabilityTabs(){const [active,setActive]=useState(0);const c=capabilities[active];return <div className="capability-explorer"><div className="capability-tabs" role="tablist" aria-label="Marketing capabilities">{capabilities.map((item,n)=><button role="tab" aria-selected={n===active} id={'cap-tab-'+n} aria-controls="capability-panel" tabIndex={n===active?0:-1} key={item.key} className={n===active?'active':''} onClick={()=>setActive(n)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(active+(e.key==='ArrowRight'?1:-1)+capabilities.length)%capabilities.length;setActive(next);document.getElementById('cap-tab-'+next)?.focus()}}}><item.icon size={18}/>{item.label}<ArrowUpRight size={15}/></button>)}</div><div className="capability-panel" id="capability-panel" role="tabpanel" aria-labelledby={'cap-tab-'+active}><div className="capability-story"><img className="capability-photo" key={c.key} src={photoUrl(servicePhoto(c.slugs[0])+'-600')} width="600" height="375" alt="" loading="lazy" decoding="async"/><span className="eyebrow">{c.label}</span><h3>{c.headline}</h3><p>{c.description}</p><ul className="check-list">{c.outcomes.map(o=><li key={o}><Check size={16}/>{o}</li>)}</ul><Link className="button" href="/contact">Request a plan for this goal <ArrowUpRight size={19}/></Link></div><div className="capability-services"><span className="eyebrow">See the services for this goal</span>{c.slugs.map(slug=>{const s=services.find(s=>s.slug===slug)!;return <Link key={slug} href={'/services/'+slug}><div><span>{s.number} / {s.group}</span><h4>{s.name}</h4><p>{s.summary}</p></div><ArrowUpRight size={25}/></Link>})}<Link className="all-services-link" href="/services">Explore all {services.length} services<ArrowRight size={18}/></Link></div></div></div>}
export { IndustryCarousel as IndustryExplorer } from '@/components/industry-carousel';
