'use client';
import {photoUrl,photoAsset,photoSources} from '@/lib/photo-assets';
import {useEffect,useRef,useState} from 'react';
import Link from '@/components/navigation-link';
import {ArrowUpRight,Check} from 'lucide-react';
import {industries} from '@/lib/client-content';

const slides=industries.filter(i=>['real-estate','hospitality','healthcare','travel','saas','ecommerce'].includes(i.slug));
const captions:Record<string,string>={'real-estate':'Help buyers take the next step.','hospitality':'Turn interest into stay enquiries.','healthcare':'Make it easier to find your care.','travel':'Help travellers choose their next trip.','saas':'Explain your product. Build interest.','ecommerce':'Help shoppers find your products.'};
export function IndustryCarousel(){const [active,setActive]=useState(0),[focus,setFocus]=useState(false),[visible,setVisible]=useState(false),[hidden,setHidden]=useState(false),[reduced,setReduced]=useState(false);const root=useRef<HTMLDivElement>(null),touch=useRef<{x:number;y:number}|null>(null);const slide=slides[active];const running=!focus&&visible&&!hidden&&!reduced;
useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches),visibility=()=>setHidden(document.hidden);update();visibility();media.addEventListener('change',update);document.addEventListener('visibilitychange',visibility);const observer='IntersectionObserver' in window?new IntersectionObserver(entries=>setVisible(entries[0]?.isIntersecting??false),{threshold:.2}):null;if(observer&&root.current)observer.observe(root.current);else setVisible(true);return()=>{observer?.disconnect();media.removeEventListener('change',update);document.removeEventListener('visibilitychange',visibility)}},[]);
useEffect(()=>{if(!running)return;const timer=window.setTimeout(()=>setActive(n=>(n+1)%slides.length),7500);return()=>window.clearTimeout(timer)},[active,running]);
useEffect(()=>{if(!visible)return;const next=slides[(active+1)%slides.length];const image=new Image();image.src=photoUrl('carousel-'+next.slug)},[active,visible]);
function go(n:number){setActive((n+slides.length)%slides.length)}
return <div ref={root} className={'industry-carousel'+(running?' is-playing':'')} role="region" aria-roledescription="carousel" aria-label="Marketing for your industry" onFocusCapture={e=>setFocus(e.target.matches(':focus-visible'))} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))setFocus(false)}} onKeyDown={e=>{if(e.key==='ArrowLeft'){e.preventDefault();go(active-1)}if(e.key==='ArrowRight'){e.preventDefault();go(active+1)}}}><div className="industry-slide" role="group" aria-roledescription="slide" aria-label={(active+1)+' of '+slides.length+': '+slide.name} onTouchStart={e=>{touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}}} onTouchEnd={e=>{if(!touch.current)return;const dx=e.changedTouches[0].clientX-touch.current.x,dy=e.changedTouches[0].clientY-touch.current.y;touch.current=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)){go(active+(dx<0?1:-1))}}}><div className="industry-slide-image"><img src={photoUrl('carousel-'+slide.slug)} width="900" height="600" alt={photoAsset('carousel-'+slide.slug)?.alt||slide.name+' business setting'} srcSet={photoSources('carousel-'+slide.slug)} sizes="(max-width:760px) 92vw, 560px" loading="eager" decoding="async"/><div className="industry-photo-caption"><span className="industry-photo-label">{slide.name}</span><p>{captions[slide.slug]}</p></div></div><div className="industry-slide-copy" key={slide.slug}><div className="industry-slide-meta"><span className="eyebrow">Built around your business</span></div><h3>{slide.headline}</h3><p>{slide.summary}</p><div className="industry-slide-issues"><span className="eyebrow">Where we can help</span>{slide.problems.slice(0,2).map(p=><div key={p}><span><Check size={16}/></span><p>{p}</p></div>)}</div><Link className="button" href={'/industries/'+slide.slug}>Explore {slide.name.toLowerCase()}<ArrowUpRight size={19}/></Link></div></div></div>}
