'use client';
import {useState} from 'react';
import {Check, CircleAlert, Minus, LockKeyhole, ArrowDown, Globe, Search, Megaphone, Users, MousePointerClick, ShieldCheck, X} from 'lucide-react';
import type {ExpertResult,AdsEvidence} from './expert-audit-report';
import type {ExpertCheck} from '@/lib/audit-expert';
import type {PerformanceComparisonResult} from '@/lib/audit-performance';
import styles from './marketing-audit-report.module.css';
const channels=[
 {id:'seo',name:'SEO',description:'Search and discovery signals',categories:['On-page SEO','Content','Discovery','Links','Images'],icon:Search},
 {id:'smm',name:'Social media',description:'Profiles and sharing readiness',categories:['Social','SMM'],icon:Users},
 {id:'ads',name:'Ads readiness',description:'Destination and measurement signals',categories:['Ads readiness'],icon:Megaphone},
 {id:'conversion',name:'Conversion',description:'Contact paths and usability',categories:['Conversion','Usability'],icon:MousePointerClick},
 {id:'technical',name:'Technical',description:'Public security headers',categories:['Security'],icon:ShieldCheck}
];
const statusLabel=(c:ExpertCheck)=>c.status==='passed'?'Passed':c.status==='unavailable'?'Needs more data':'Review';
export function MarketingAuditReport({report:r,performance,ads}:{report:ExpertResult;performance:PerformanceComparisonResult;ads:AdsEvidence|null}){
 const [filter,setFilter]=useState('all');const [download,setDownload]=useState(false);
 const priorities=r.checks.filter(c=>c.status==='review').sort((a,b)=>['High','Medium','Low'].indexOf(a.priority)-['High','Medium','Low'].indexOf(b.priority)).slice(0,5);
 const totals={passed:r.checks.filter(c=>c.status==='passed').length,review:r.checks.filter(c=>c.status==='review').length,unavailable:r.checks.filter(c=>c.status==='unavailable').length};
 return <div className={styles.report}>
 <header className={styles.cover}><div><span className={styles.kicker}>DIGITAL MARKETING BUREAU · WEBSITE INTELLIGENCE</span><h2>One website. A clearer marketing picture.</h2><a className={styles.domain} href={r.url} target="_blank" rel="noopener noreferrer"><Globe size={18}/>{new URL(r.url).hostname}</a><p>{r.title||'Page title not declared'}</p><small>Checked {new Date(r.checkedAt).toLocaleString()} · Submitted-page audit</small></div><div className={styles.overall}><strong>{r.score}<span>/100</span></strong><span>Observable website checks</span><small>Not an ad-performance or Google ranking score</small></div></header>
 <div className={styles.toolbar}><p><span><Check size={16}/>{totals.passed} passed</span><span><CircleAlert size={16}/>{totals.review} to review</span><span><Minus size={16}/>{totals.unavailable} need more data</span></p><button className={styles.download} onClick={()=>setDownload(true)}><LockKeyhole size={17}/>Report download</button></div>
 <div className={styles.cards}>{channels.map(channel=>{const checks=r.checks.filter(c=>channel.categories.includes(c.category));const measured=checks.filter(c=>c.status!=='unavailable');const score=measured.length?Math.round(measured.filter(c=>c.status==='passed').length/measured.length*100):null;const Icon=channel.icon;return <a key={channel.id} href={'#report-'+channel.id} className={styles.scoreCard}><Icon size={22}/><h3>{channel.name}</h3><strong>{score===null?'—':score}<small>{score===null?'No data':'/100'}</small></strong><p>{channel.description}</p><small>{measured.length} measured · {checks.length-measured.length} unavailable</small><ArrowDown size={15}/></a>})}</div>
 <p className={styles.scope}>Scores summarize observable page checks only. Missing social profiles or tracking data are not treated as proof that you have no social presence or advertising. Campaign performance needs authorized account data.</p>
 <section className={styles.panel}><span className={styles.kicker}>START HERE</span><h3>Your next priorities</h3><p>Review these findings first. Confirm each issue before making a change.</p><div className={styles.priorityGrid}>{priorities.length?priorities.map((c,i)=><article key={c.id}><span className={styles.priorityNumber}>{String(i+1).padStart(2,'0')}</span><small>{c.category} · {c.priority} priority</small><h4>{c.name}</h4><p>{c.fix}</p></article>):<p>No priority issues identified in the measured checks. Manual review is still useful.</p>}</div></section>
 <section className={styles.panel}><h3>Website details</h3><dl className={styles.facts}>{[['Audited URL',r.url],['Page title',r.title||'Not declared'],['Meta description',r.description||'Not declared'],['Approximate words',r.wordCount],['Images',r.facts.images],['Internal / external links',r.facts.internalLinks+' / '+r.facts.externalLinks],['HTML response',Math.round(r.facts.htmlBytes/1024)+' KB'],['Contact destinations',r.marketing.actionLinks]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>
 <nav className={styles.filters} aria-label="Filter findings">{[['all','All findings'],['review','Needs attention'],['passed','Passed'],['unavailable','More data needed']].map(([value,label])=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</nav>
 {channels.map(channel=>{const all=r.checks.filter(c=>channel.categories.includes(c.category));const checks=all.filter(c=>filter==='all'||c.status===filter);return <section id={'report-'+channel.id} className={styles.panel} key={channel.id}><div className={styles.sectionTitle}><channel.icon size={24}/><div><h3>{channel.name} findings</h3><p>{channel.description}</p></div></div>{channel.id==='smm'&&<div className={styles.evidence}><h4>Social links discovered</h4>{r.marketing.profiles.length?r.marketing.profiles.map(p=><a key={p.url} href={p.url} target="_blank" rel="noopener noreferrer">{p.platform}<span>{p.url}</span></a>):<p>No supported profile links found in the returned HTML.</p>}<small>Profile ownership, posts, engagement, reach and follower counts have not been verified.</small></div>}{channel.id==='ads'&&<div className={styles.evidence}><h4>Tracking markers</h4><div className={styles.markers}>{r.marketing.tracking.map(t=><span key={t.name}>{t.found?<Check size={15}/>:<Minus size={15}/>}<b>{t.name}</b><small>{t.found?'Marker found':'Not observed'}</small></span>)}</div><p>Tags may load through JavaScript or consent. Presence does not confirm working conversions. Ad spend, ROAS, targeting and account health require account access.</p>{ads?.records.map(a=><p key={a.source}><strong>{a.source}: {a.status}</strong> · {a.detail}</p>)}</div>}{checks.length?checks.map(c=><details className={styles.finding} key={c.id} data-status={c.status}><summary><span className={styles.status}>{c.status==='passed'?<Check size={18}/>:c.status==='unavailable'?<Minus size={18}/>:<CircleAlert size={18}/>}</span><strong>{c.name}</strong><small>{statusLabel(c)}</small></summary><div><h4>What we found</h4><p>{c.detail}</p>{c.status!=='passed'&&<><h4>Recommended next step</h4><p>{c.fix}</p></>}</div></details>):<p>No findings match this filter in this category.</p>}</section>})}
 <section className={styles.panel}><h3>Metadata, headings and discovery files</h3><details className={styles.finding}><summary><strong>Metadata inventory</strong><small>{r.metadata.filter(m=>m.value).length} declared values</small></summary><div className={styles.tableScroll}><table><thead><tr><th>Tag</th><th>Value</th><th>Declarations</th></tr></thead><tbody>{r.metadata.map(m=><tr key={m.name}><th>{m.name}</th><td>{m.value||'Not declared'}</td><td>{m.count}</td></tr>)}</tbody></table></div></details><details className={styles.finding}><summary><strong>Content terms and distribution</strong><small>Observed terms</small></summary><div className={styles.tableScroll}><p>Most frequent terms in the returned content. These are not verified target keywords, search volumes or ranking data.</p><table><thead><tr><th>Term</th><th>Mentions</th><th>Title</th><th>Description</th><th>Headings</th></tr></thead><tbody>{r.keywords.map(k=><tr key={k.term}><td>{k.term}</td><td>{k.count}</td><td>{k.title?'Yes':'No'}</td><td>{k.description?'Yes':'No'}</td><td>{k.headings?'Yes':'No'}</td></tr>)}</tbody></table></div></details><details className={styles.finding}><summary><strong>Structured data inventory</strong><small>{r.structuredData.blocks} blocks</small></summary><div><p>{r.structuredData.types.join(', ')||'No schema types discovered'}</p><p>{r.structuredData.invalid} JSON syntax errors. Property validity and rich-result eligibility require a dedicated schema review.</p></div></details><details className={styles.finding}><summary><strong>Heading structure</strong><small>{r.facts.headings.length} headings</small></summary><div>{r.facts.headings.map((h,i)=><p key={i}><b>H{h.level}</b> · {h.text||'Empty heading'}</p>)}</div></details>{r.files.map(f=><details className={styles.finding} key={f.name}><summary><strong>{f.name}</strong><small>{f.status}</small></summary><div><p>{f.url}</p><p>{f.note}</p>{f.entries!==null&&<p>{f.entries} URL entries in the retrieved excerpt</p>}{f.preview&&<pre>{f.preview}</pre>}</div></details>)}</section>
 <section className={styles.panel}><h3>Performance evidence</h3><p>Measured separately from the HTML-readiness scores above.</p><div className={styles.performance}>{(['mobile','desktop'] as const).map(device=>{const p=performance[device];return <article key={device}><h4>{device==='mobile'?'Mobile':'Desktop'}</h4><strong>{p?.lab?.score!==null&&p?.lab?.score!==undefined?p.lab.score+'/100':'Awaiting measurement'}</strong><p>{p?.lab?'LCP: '+(p.lab.lcp===null?'Unavailable':(p.lab.lcp/1000).toFixed(2)+' s')+' · CLS: '+(p.lab.cls??'Unavailable'):p?.message||'Mobile and desktop tests start automatically; results appear as they become available.'}</p><small>Real-user data: {p?.field?.status==='ready'?'Available':'Not available yet'}</small></article>})}</div></section>
 <section className={styles.downloadPanel}><LockKeyhole size={28}/><div><h3>Your report, ready to review.</h3><p>Explore the findings here. A paid downloadable report will be available after checkout is configured.</p></div><button className={styles.download} onClick={()=>setDownload(true)}>Download options</button></section>
 <p className={styles.scope}>{r.scope} This report does not establish rankings, actual social performance, campaign profitability or legal compliance.</p>
 {download&&<div className={styles.paymentNotice} role="status"><button aria-label="Close download notice" onClick={()=>setDownload(false)}><X size={18}/></button><LockKeyhole size={25}/><h3>Paid downloads are being configured</h3><p>Your full online report remains available. Download checkout is not active yet, and no payment can be taken here.</p><button className={styles.download} onClick={()=>setDownload(false)}>Continue reviewing my report</button></div>}
 </div>;
}
