import {Search,Target,MousePointer2,Filter,LayoutTemplate,SlidersHorizontal,Workflow,ScanSearch,FileSearch,MapPin,Building2,Route,TrendingUp,BookOpen,Sparkles,Users,BriefcaseBusiness,Repeat2,Mail,ChartNoAxesCombined,Gauge,ClipboardCheck,Waypoints,Layers3,MessagesSquare,UserRoundPen,PanelsTopLeft,House,Hotel,HeartPulse,Plane,Boxes,ShoppingBag,GraduationCap,Truck,Sun,ArrowUpRight,Check} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
type Scene={title:string;tag:string;steps:[string,string,string];icon:LucideIcon;kind:string};
const scenes:Record<string,Scene>={
 'online-reputation-management':{title:'Respond with clarity and care',tag:'Reputation / Customer feedback',steps:['Listen to feedback','Agree a response','Follow up clearly'],icon:MessagesSquare,kind:'social'},
 'home-plan':{title:'A plan built around your business',tag:'DMB / Growth planning',steps:['Customer priorities','Connected channels','Clear next step'],icon:Layers3,kind:'network'},
 'home-priority':{title:'Choose the right next improvement',tag:'DMB / Website experience',steps:['Useful offer','Clear service pages','Enquiry journey'],icon:LayoutTemplate,kind:'page'},

 'google-ads-audit':{title:'Find the wasted spend',tag:'Paid search / Audit',steps:['Search terms','Budget review','Priority fixes'],icon:ScanSearch,kind:'search'},
 'google-ads-management':{title:'Reach buying intent',tag:'Paid search / Campaigns',steps:['Customer intent','Relevant ad','Enquiry page'],icon:Target,kind:'campaign'},
 'paid-social-advertising':{title:'Creative meets audience',tag:'Paid social / Creative',steps:['Audience','Creative test','Enquiry'],icon:MousePointer2,kind:'social'},
 'lead-quality-optimization':{title:'Qualify the next enquiry',tag:'Lead quality / Screening',steps:['New enquiry','Fit & intent','Sales feedback'],icon:Filter,kind:'funnel'},
 'landing-page-design':{title:'A clearer next step',tag:'Conversion / Page design',steps:['Clear offer','Useful proof','Enquiry form'],icon:LayoutTemplate,kind:'page'},
 'conversion-rate-audit':{title:'Remove the friction',tag:'Conversion / Review',steps:['Visitor journey','Friction points','Test priorities'],icon:SlidersHorizontal,kind:'funnel'},
 'conversion-tracking-setup':{title:'Connect every touchpoint',tag:'Measurement / Events',steps:['Customer action','Event tracking','Useful reporting'],icon:Workflow,kind:'network'},
 'technical-seo-audit':{title:'Build a sound foundation',tag:'Search / Technical',steps:['Crawl access','Index signals','Technical fixes'],icon:ScanSearch,kind:'search'},
 'on-page-seo':{title:'Match the search intent',tag:'Search / On-page',steps:['Customer question','Page structure','Clear answers'],icon:FileSearch,kind:'document'},
 'local-seo':{title:'Be found close to home',tag:'Search / Local',steps:['Service area','Local relevance','Customer enquiry'],icon:MapPin,kind:'map'},
 'google-business-profile':{title:'Make your presence clear',tag:'Local / Business profile',steps:['Business details','Services & updates','Contact action'],icon:Building2,kind:'map'},
 'seo-migration-support':{title:'Move with a clear map',tag:'Search / Migration',steps:['Existing URLs','Redirect map','Launch checks'],icon:Route,kind:'network'},
 'organic-traffic-recovery':{title:'Understand what changed',tag:'Search / Recovery',steps:['Search history','Lost visibility','Recovery priorities'],icon:TrendingUp,kind:'chart'},
 'content-strategy':{title:'Answer real questions',tag:'Content / Strategy',steps:['Buyer questions','Content plan','Service connections'],icon:BookOpen,kind:'document'},
 'ai-search-visibility':{title:'Make expertise discoverable',tag:'AI search / Visibility',steps:['Clear entities','Useful answers','Reliable sources'],icon:Sparkles,kind:'network'},
 'b2b-lead-generation':{title:'Reach the right business',tag:'B2B / Demand',steps:['Customer fit','Relevant offer','Sales conversation'],icon:Users,kind:'funnel'},
 'linkedin-advertising':{title:'Speak to decision makers',tag:'B2B / LinkedIn',steps:['Professional audience','Specific message','Lead form'],icon:BriefcaseBusiness,kind:'social'},
 'retargeting-campaigns':{title:'Continue the conversation',tag:'Paid media / Retargeting',steps:['Previous interest','Relevant reminder','Return visit'],icon:Repeat2,kind:'campaign'},
 'email-lead-nurturing':{title:'Help interest move forward',tag:'Email / Nurturing',steps:['Customer question','Useful follow-up','Next action'],icon:Mail,kind:'mail'},
 'analytics-dashboards':{title:'See the connected picture',tag:'Analytics / Reporting',steps:['Channel activity','Useful enquiries','Business context'],icon:ChartNoAxesCombined,kind:'chart'},
 'website-speed-optimization':{title:'Less waiting. More clarity.',tag:'Website / Performance',steps:['Loading review','Asset priorities','Real-world checks'],icon:Gauge,kind:'speed'},
 'seo-second-opinion':{title:'A fresh view of your plan',tag:'Search / Independent review',steps:['Current advice','Evidence review','Clear recommendation'],icon:ClipboardCheck,kind:'document'},
 'marketing-automation':{title:'A smoother enquiry journey',tag:'Marketing / Automation',steps:['New enquiry','Agreed workflow','Team follow-up'],icon:Waypoints,kind:'network'},
 'paid-media-strategy':{title:'Give every channel a role',tag:'Paid media / Strategy',steps:['Business goal','Channel plan','Measurement'],icon:Layers3,kind:'campaign'},
 'social-media-strategy':{title:'A purpose for every post',tag:'Social / Strategy',steps:['Audience needs','Content pillars','Publishing plan'],icon:MessagesSquare,kind:'social'},
 'social-profile-setup':{title:'A presence that feels like you',tag:'Social / Profiles',steps:['Brand details','Profile structure','Contact links'],icon:UserRoundPen,kind:'page'},
 'social-media-content-management':{title:'A consistent brand story',tag:'Social / Content',steps:['Topic planning','Creative production','Agreed publishing'],icon:PanelsTopLeft,kind:'social'},
 'real-estate':{title:'From property to viewing',tag:'Industry / Real estate',steps:['Property discovery','Listing details','Viewing enquiry'],icon:House,kind:'property'},
 'hospitality':{title:'Make the stay worth exploring',tag:'Industry / Hospitality',steps:['Stay discovery','Guest experience','Booking enquiry'],icon:Hotel,kind:'property'},
 'healthcare':{title:'A clearer path to care',tag:'Industry / Healthcare',steps:['Care needs','Service information','Appointment enquiry'],icon:HeartPulse,kind:'network'},
 'travel':{title:'Turn discovery into a journey',tag:'Industry / Travel',steps:['Destination','Trip details','Travel enquiry'],icon:Plane,kind:'map'},
 'saas':{title:'Show the product value',tag:'Industry / SaaS',steps:['Customer problem','Product experience','Demo request'],icon:Boxes,kind:'page'},
 'ecommerce':{title:'Help shoppers choose',tag:'Industry / Ecommerce',steps:['Product discovery','Product details','Checkout journey'],icon:ShoppingBag,kind:'social'},
 'professional-services':{title:'Expertise, clearly explained',tag:'Industry / Professional',steps:['Customer needs','Relevant expertise','Business enquiry'],icon:BriefcaseBusiness,kind:'document'},
 'home-services':{title:'Reach the next local job',tag:'Industry / Home services',steps:['Service area','Customer need','Quote enquiry'],icon:House,kind:'map'},
 'education':{title:'Help learners choose a path',tag:'Industry / Education',steps:['Course discovery','Learning options','Admission enquiry'],icon:GraduationCap,kind:'document'},
 'recruitment':{title:'Connect roles with the right fit',tag:'Industry / Recruitment',steps:['Role requirements','Candidate fit','Hiring conversation'],icon:Users,kind:'funnel'},
 'logistics':{title:'Make your coverage clear',tag:'Industry / Logistics',steps:['Delivery needs','Service coverage','Quote request'],icon:Truck,kind:'map'},
 'solar':{title:'Connect interest with assessment',tag:'Industry / Solar & energy',steps:['Property needs','Installation options','Assessment enquiry'],icon:Sun,kind:'property'},
};
function resolve(name:string):Scene{const keys=Object.keys(scenes).sort((a,b)=>b.length-a.length);const key=keys.find(k=>name.includes(k));if(key)return scenes[key];if(/clicks/.test(name))return scenes['google-ads-audit'];if(/traffic/.test(name))return scenes['conversion-rate-audit'];if(/qualified/.test(name))return scenes['lead-quality-optimization'];if(/hospitality/.test(name))return scenes.hospitality;if(/professional/.test(name))return scenes['professional-services'];return {title:/market|global|international/.test(name)?'Local context. Global reach.':'A connected growth plan',tag:'DMB / Marketing systems',steps:['Business needs','Focused plan','Useful enquiries'],icon:/market|global|international/.test(name)?MapPin:Layers3,kind:/market|global|international/.test(name)?'map':'network'}}
const mint='#b4fd83',muted='#a4bbb1',line='#37594c';
export function PremiumVisual({name,compact=false,alt}:{name:string;compact?:boolean;alt?:string}){const s=resolve(name);const Icon=s.icon;const seed=Array.from(name).reduce((a,c)=>a+c.charCodeAt(0),0);return <div className={'premium-visual premium-'+s.kind+(compact?' premium-compact':'')} data-visual-key={name}>
 <svg viewBox="0 0 720 480" width="720" height="480" role="img" aria-label={alt||`${s.title}: conceptual illustration of ${s.steps.join(', ')}`}>
 <rect width="720" height="480" fill="#0d3029"/><path d="M0 96H720M0 192H720M0 288H720M0 384H720M120 0V480M240 0V480M360 0V480M480 0V480M600 0V480" stroke="#b4fd83" opacity=".035"/>
 <circle cx={590+seed%35} cy="190" r="170" fill="#b4fd83" opacity=".025"/><circle cx="590" cy="190" r="125" fill="none" stroke={line} opacity=".3"/>
 <text x="34" y="41" fill={muted} fontSize="12" letterSpacing="2" fontFamily="Arial,sans-serif">{s.tag.toUpperCase()}</text><text x="665" y="41" fill={mint} fontSize="13" textAnchor="end" fontFamily="Arial,sans-serif">DMB</text>
 <text x="34" y="82" fill="#f1f6ec" fontSize="26" fontWeight="600" fontFamily="Arial,sans-serif">{s.title}</text>
 <g className="premium-scene">
 {s.kind==='search'&&<><rect x="62" y="124" width="420" height="226" rx="14" fill="#f0f4ec"/><rect x="84" y="146" width="375" height="40" rx="20" fill="#dae5d8"/><Search x="101" y="157" size={18} color="#365b48"/><text x="131" y="172" fill="#365b48" fontSize="13" fontFamily="Arial">{s.steps[0]}</text>{[0,1,2].map(i=><g key={i}><rect x="89" y={210+i*42} width={200-i*27} height="8" rx="4" fill={i===0?'#315c43':'#c1d2bf'}/><rect x="89" y={227+i*42} width={288-i*22} height="5" rx="2" fill="#d2decf"/></g>)}<rect x="418" y="215" width="215" height="112" rx="13" fill="#244839" stroke={line}/><Icon x="440" y="236" size={32} color={mint}/><text x="440" y="301" fill="#e7f1e2" fontSize="13" fontFamily="Arial">{s.steps[2]}</text><Check x="591" y="240" size={23} color={mint}/></>}
 {s.kind==='campaign'&&<><circle cx="338" cy="234" r="108" fill="none" stroke={line}/><circle cx="338" cy="234" r="70" fill="none" stroke={line}/><circle cx="338" cy="234" r="35" fill="#284d3a"/><Icon x="319" y="215" size={38} color={mint}/><path d="M130 270L315 244M369 222L566 163M366 249L566 299" stroke={mint} strokeWidth="2" opacity=".45"/><circle className="premium-pulse" cx="338" cy="234" r="49" fill="none" stroke={mint} opacity=".35"/>{[[66,249],[499,135],[499,282]].map(([x,y],i)=><g key={i}><rect x={x} y={y} width="161" height="63" rx="10" fill="#183c30" stroke={line}/><text x={x+16} y={y+36} fill="#edf5e8" fontSize="12" fontFamily="Arial">{s.steps[i]}</text></g>)}</>}
 {s.kind==='social'&&<>{s.steps.map((label,i)=><g key={label} transform={`translate(${90+i*177},${147+(i===1?-18:12)}) rotate(${(i-1)*4},78,92)`}><rect width="155" height="190" rx="14" fill={i===1?'#f0f4ec':'#1c4133'} stroke={line}/><circle cx="22" cy="22" r="7" fill={i===1?'#2d5741':mint}/><rect x="37" y="18" width="63" height="6" rx="3" fill={i===1?'#bdcebb':line}/><rect x="13" y="43" width="129" height="90" rx="8" fill={i===1?'#d9e7d4':'#2a503c'}/><Icon x="53" y="67" size={42} color={i===1?'#254b36':mint} strokeWidth={1.3}/><text x="15" y="155" fill={i===1?'#244735':'#e6f1e0'} fontSize="11" fontFamily="Arial">{label}</text><rect x="15" y="168" width={85-i*12} height="4" rx="2" fill={i===1?'#c0d0ba':line}/></g>)}</>}
 {s.kind==='funnel'&&<>{s.steps.map((label,i)=><g key={label}><path d={`M${110+i*64} ${126+i*69}H${610-i*64}L${588-i*64} ${181+i*69}H${132+i*64}Z`} fill={i===2?mint:'#1e4535'} stroke={i===2?mint:line}/><text x="360" y={160+i*69} textAnchor="middle" fill={i===2?'#153d29':'#e8f2e2'} fontSize="14" fontFamily="Arial">{label}</text></g>)}<Icon x="342" y="353" size={35} color={mint}/></>}
 {s.kind==='page'&&<><rect x="95" y="122" width="428" height="231" rx="12" fill="#f0f4ec"/><path d="M95 156H523" stroke="#d0deca"/>{[0,1,2].map(i=><circle key={i} cx={113+i*12} cy="140" r="3" fill="#9db396"/>)}<rect x="117" y="180" width="155" height="13" rx="3" fill="#315c43"/><rect x="117" y="204" width="181" height="6" rx="3" fill="#bacdb5"/><rect x="117" y="220" width="158" height="6" rx="3" fill="#cad9c5"/><rect x="117" y="249" width="101" height="30" rx="5" fill={mint}/><text x="128" y="269" fill="#254d35" fontSize="11" fontFamily="Arial">{s.steps[2]}</text><rect x="326" y="178" width="173" height="117" rx="8" fill="#dce8d4"/><Icon x="386" y="209" size={52} color="#375d43" strokeWidth={1.2}/><rect x="415" y="308" width="188" height="49" rx="9" fill="#254b37" stroke={line}/><Check x="433" y="322" size={18} color={mint}/><text x="462" y="337" fill="#e5f1df" fontSize="12" fontFamily="Arial">{s.steps[0]}</text></>}
 {s.kind==='network'&&<><path d="M150 166L360 240L576 163M150 320L360 240L576 319" fill="none" stroke={line} strokeWidth="2"/><circle cx="360" cy="240" r="58" fill="#234c36" stroke="#557455"/><Icon x="338" y="218" size={44} color={mint}/>{[[79,135],[485,135],[79,291],[485,291]].map(([x,y],i)=><g key={i}><rect x={x} y={y} width="154" height="56" rx="10" fill="#153a2c" stroke={line}/><text x={x+77} y={y+33} textAnchor="middle" fill="#e8f1e2" fontSize="12" fontFamily="Arial">{i===3?'Next action':s.steps[i]}</text></g>)}<circle className="premium-pulse" cx="360" cy="240" r="70" fill="none" stroke={mint} opacity=".3"/></>}
 {s.kind==='document'&&<><rect x="154" y="126" width="266" height="227" rx="12" fill="#edf3e7" transform="rotate(-4 287 239)"/><rect x="207" y="137" width="267" height="228" rx="12" fill="#f7f8f1"/><Icon x="232" y="157" size={31} color="#335942"/>{s.steps.map((label,i)=><g key={i}><rect x="231" y={209+i*43} width="6" height="19" rx="2" fill={i===1?'#8ebe65':'#bdcfb2'}/><text x="250" y={224+i*43} fill="#36533d" fontSize="12" fontFamily="Arial">{label}</text><rect x="250" y={235+i*43} width={150-i*18} height="4" rx="2" fill="#d4dfcb"/></g>)}<circle cx="491" cy="291" r="42" fill="#274c37" stroke={line}/><Check x="473" y="273" size={36} color={mint}/></>}
 {s.kind==='map'&&<><path d="M72 145L223 124L382 155L532 130L643 154V326L512 348L370 320L219 350L72 321Z" fill="#183e30" stroke={line}/><path d="M223 124L219 350M382 155L370 320M532 130L512 348M83 274L223 214L382 269L532 203L635 256" stroke="#42624d" fill="none"/><path d={`M169 260Q340 ${112+seed%40} 558 260`} stroke={mint} fill="none" strokeWidth="2" strokeDasharray="5 8"/><circle cx="169" cy="260" r="9" fill={mint}/><Icon x="345" y="174" size={56} color={mint} strokeWidth={1.3}/><circle cx="558" cy="260" r="9" fill={mint}/><rect x="246" y="300" width="228" height="48" rx="8" fill="#f0f4e9"/><text x="360" y="330" textAnchor="middle" fill="#31513c" fontSize="13" fontFamily="Arial">{s.steps[1]}</text></>}
 {s.kind==='chart'&&<><rect x="89" y="125" width="540" height="235" rx="14" fill="#173b2e" stroke={line}/><text x="112" y="156" fill={muted} fontSize="12" fontFamily="Arial">{s.steps[0]}</text><path d="M122 195H466M122 242H466M122 289H466" stroke={line} opacity=".6"/>{[44,75,59,107,84,129,101].map((h,i)=><rect key={i} x={134+i*45} y={325-h} width="21" height={h} rx="4" fill={i===5?mint:'#416b4e'}/>)}<Icon x="521" y="207" size={48} color={mint} strokeWidth={1.2}/><text x="489" y="289" fill={muted} fontSize="11" fontFamily="Arial">{s.steps[2]}</text></>}
 {s.kind==='mail'&&<><rect x="103" y="138" width="343" height="204" rx="13" fill="#edf4e7"/><path d="M107 151L274 252L442 151" stroke="#a8bd9e" fill="none" strokeWidth="2"/><Mail x="251" y="260" size={40} color="#3b6046"/>{s.steps.map((label,i)=><g key={i}><rect x="432" y={151+i*66} width="208" height="51" rx="9" fill="#214532" stroke={line}/><circle cx="452" cy={177+i*66} r="4" fill={mint}/><text x="468" y={181+i*66} fill="#e8f2e2" fontSize="12" fontFamily="Arial">{label}</text></g>)}</>}
 {s.kind==='speed'&&<><path d="M201 309A159 159 0 0 1 519 309" stroke={line} strokeWidth="15" fill="none" strokeLinecap="round"/><path d="M201 309A159 159 0 0 1 455 183" stroke={mint} strokeWidth="15" fill="none" strokeLinecap="round"/><path d="M360 306L436 218" stroke="#edf5e7" strokeWidth="5" strokeLinecap="round"/><circle cx="360" cy="306" r="13" fill={mint}/><Icon x="340" y="212" size={40} color={mint}/><text x="360" y="358" textAnchor="middle" fill={muted} fontSize="13" fontFamily="Arial">{s.steps[2]}</text></>}
 {s.kind==='property'&&<><path d="M159 259L159 203L283 132L407 203V314H159Z" fill="#264c38" stroke="#527554"/><path d="M283 132V314M159 203L283 272L407 203" fill="none" stroke="#527554"/><Icon x="241" y="183" size={67} color={mint} strokeWidth={1.2}/><path d="M202 337L328 367L467 297" fill="none" stroke={line}/><rect x="429" y="180" width="205" height="145" rx="13" fill="#f0f4e8"/><text x="449" y="208" fill="#365b41" fontSize="11" fontFamily="Arial">{s.steps[0]}</text><path d="M449 225H607M449 240H582" stroke="#c4d3bc" strokeWidth="5" strokeLinecap="round"/><rect x="449" y="263" width="165" height="36" rx="6" fill={mint}/><text x="461" y="286" fill="#264a32" fontSize="11" fontFamily="Arial">{s.steps[2]}</text></>}
 </g>
 <path d="M34 406H686" stroke={line}/>{s.steps.map((label,i)=><g key={label}><text x={35+i*225} y="441" fill={mint} fontSize="11" fontFamily="Arial">0{i+1}</text><text x={60+i*225} y="441" fill={muted} fontSize="11" fontFamily="Arial">{label}</text></g>)}
 </svg></div>}
