import {Schema} from '@/components/blocks';
import {origin} from '@/lib/site';
import {HeroAudit} from '@/components/hero-audit';
import {AdsAuditWorkspace} from '@/components/ads-audit-workspace';
import {SocialAuditWorkspace} from '@/components/social-audit-workspace';
import {LocalAuditWorkspace} from '@/components/local-audit-workspace';
import {auditForService} from '@/lib/audit-tools';
import styles from './service-audit-option.module.css';
export function ServiceAuditOption({slug}:{slug:string}){const audit=auditForService(slug);const kind=slug==='local-seo'?'local':/social|reputation/.test(slug)&&slug!=='paid-social-advertising'?'social':/ads|advertising|paid|retarget/.test(slug)?'ads':/seo|search|content/.test(slug)?'seo':'all';const primary=['google-ads-management','seo-bureau','social-media-content-management'].includes(slug);return <section id="service-audit" className={styles.embedded}><details open={primary}><summary><span>FREE AUDIT &amp; OPTIMIZATION</span><h2>{audit.label}</h2><p>Use the tool here, then choose the service scope you need.</p></summary><div className={styles.workspace}>{kind==='local'?<LocalAuditWorkspace/>:kind==='ads'?<AdsAuditWorkspace initialPlatform={slug==='paid-social-advertising'?'meta':slug==='linkedin-advertising'?'linkedin':'google'}/>:kind==='social'?<SocialAuditWorkspace/>:<HeroAudit fullPage auditKind={kind}/>}</div></details><Schema data={{'@context':'https://schema.org','@type':'WebApplication',name:audit.label,url:origin+(slug==='seo-bureau'?'/seo-bureau':'/services/'+slug)+'#service-audit',applicationCategory:'BusinessApplication',operatingSystem:'Web browser',offers:{'@type':'Offer',price:0,priceCurrency:'USD'},publisher:{'@id':origin+'/#organization'}}}/></section>}

const sections:Record<string,{title:string;body:string}[]>={
 'google-ads-management':[{title:'Google Ads audit',body:'Review account evidence, search terms, campaign settings, budget use and conversion measurement. Choose an audit-only scope if you want priorities before ongoing work.'},{title:'Campaign setup and ongoing management',body:'Build or improve campaigns, refine ad messages and queries, and review useful inquiries. Advertising spend and the management fee are agreed separately.'}],
 'local-seo':[{title:'Local website and search optimization',body:'Align genuine service areas, useful local pages and consistent business details with customer searches.'},{title:'Google Business Profile optimization',body:'Review eligibility, categories, services, approved photos, contact links and review response processes. This can be booked as a focused scope.'}],
 'conversion-optimization':[{title:'Lead quality optimization',body:'Define suitable customers, trace poor-fit inquiries and test clearer offer criteria or form questions with sales feedback.'},{title:'Conversion rate optimization',body:'Review the offer, customer questions, mobile experience and inquiry steps. Prioritize changes and a test plan based on available visitor evidence.'},{title:'GA4 and conversion tracking setup',body:'Define useful events, configure agreed tags and test successful submissions. Document what is measured and distinguish real completions from button clicks.'}],
 'social-media-content-management':[{title:'Social media strategy',body:'Agree suitable platforms, customer questions, content themes and a publishing plan.'},{title:'Instagram and Facebook optimization',body:'Improve approved profile names, biographies, business descriptions, services and contact paths.'},{title:'YouTube SEO',body:'Review channel information, video titles, descriptions and viewer actions around relevant topics.'},{title:'Content management',body:'Agree formats, post volume, revisions, approvals and scheduling for ongoing publishing.'}],
 'technical-seo-audit':[{title:'Technical SEO audit',body:'Investigate crawling, indexing, canonicals, redirects and site structure, with affected URLs and fix priorities.'},{title:'Independent SEO review',body:'Review existing reports and proposed tasks, explain their supporting evidence and identify questions to resolve.'}],
 'on-page-seo':[{title:'Content strategy and briefs',body:'Map buyer questions and commercial searches to existing pages or useful new content. Prioritize topics and internal links.'},{title:'On-page optimization',body:'Improve agreed titles, headings, descriptions and service copy. Full content production is scoped separately.'}],
 'marketing-automation':[{title:'Workflow setup',body:'Connect forms, routing, CRM handoff, confirmations and reminders, with tested failures and clear ownership.'},{title:'Email lead nurturing',body:'Plan approved sequences around customer questions, triggers and the next buying decision. Agree sending access and contact permissions.'}],
 'paid-media-strategy':[{title:'Paid media strategy',body:'Choose channel roles, test budgets, launch requirements and review criteria before campaign work.'},{title:'Retargeting setup and management',body:'Define eligible audiences, exclusions, relevant messages and frequency reviews, subject to platform and consent requirements.'}]

};
export function ServiceScopes({slug}:{slug:string}){const items=sections[slug];if(!items)return null;return <section className="content-section"><h2>Choose the scope you need.</h2>{items.map(item=><div key={item.title}><h3>{item.title}</h3><p>{item.body}</p></div>)}</section>}

