import Link from '@/components/navigation-link';
import {auditForService} from '@/lib/audit-tools';
import styles from './service-audit-option.module.css';
export function ServiceAuditOption({slug}:{slug:string}){const audit=auditForService(slug);return <section className={styles.option}><div><span>CHECK BEFORE YOU PLAN</span><h2>Start with an audit.</h2><p>Review the relevant website signals or supply account evidence in the tool. Use the findings to choose the work you need.</p></div><Link className="button" href={audit.href+'?service='+encodeURIComponent(slug)}>{audit.label} →</Link></section>}
const sections:Record<string,{title:string;body:string}[]>={
 'google-ads-management':[{title:'Google Ads audit',body:'Review account evidence, search terms, campaign settings, budget use and conversion measurement. Choose an audit-only scope if you want priorities before ongoing work.'},{title:'Campaign setup and ongoing management',body:'Build or improve campaigns, refine ad messages and queries, and review useful inquiries. Advertising spend and the management fee are agreed separately.'}],
 'local-seo':[{title:'Local website and search optimization',body:'Align genuine service areas, useful local pages and consistent business details with customer searches.'},{title:'Google Business Profile optimization',body:'Review eligibility, categories, services, approved photos, contact links and review response processes. This can be booked as a focused scope.'}],
 'conversion-optimization':[{title:'Lead quality optimization',body:'Define suitable customers, trace poor-fit inquiries and test clearer offer criteria or form questions with sales feedback.'},{title:'Conversion rate optimization',body:'Review the offer, customer questions, mobile experience and inquiry steps. Prioritize changes and a test plan based on available visitor evidence.'},{title:'GA4 and conversion tracking setup',body:'Define useful events, configure agreed tags and test successful submissions. Document what is measured and distinguish real completions from button clicks.'}],
 'social-media-content-management':[{title:'Social media strategy',body:'Agree suitable platforms, customer questions, content themes and a publishing plan.'},{title:'Instagram and Facebook optimization',body:'Improve approved profile names, biographies, business descriptions, services and contact paths.'},{title:'YouTube SEO',body:'Review channel information, video titles, descriptions and viewer actions around relevant topics.'},{title:'Content management',body:'Agree formats, post volume, revisions, approvals and scheduling for ongoing publishing.'}],
 'technical-seo-audit':[{title:'Technical SEO audit',body:'Investigate crawling, indexing, canonicals, redirects and site structure, with affected URLs and fix priorities.'},{title:'Independent SEO review',body:'Review existing reports and proposed tasks, explain their supporting evidence and identify questions to resolve.'}],
 'on-page-seo':[{title:'Content strategy and briefs',body:'Map buyer questions and commercial searches to existing pages or useful new content. Prioritize topics and internal links.'},{title:'On-page optimization',body:'Improve agreed titles, headings, descriptions and service copy. Full content production is scoped separately.'}],
 'marketing-automation':[{title:'Workflow setup',body:'Connect forms, routing, CRM handoff, confirmations and reminders, with tested failures and clear ownership.'},{title:'Email lead nurturing',body:'Plan approved sequences around customer questions, triggers and the next buying decision. Agree sending access and contact permissions.'}],
 'paid-media-strategy':[{title:'Paid media strategy',body:'Choose channel roles, test budgets, launch requirements and review criteria before campaign work.'},{title:'Retargeting setup and management',body:'Define eligible audiences, exclusions, relevant messages and frequency reviews, subject to platform and consent requirements.'}]

};
export function ServiceScopes({slug}:{slug:string}){const items=sections[slug];if(!items)return null;return <section className="content-section"><h2>Choose the scope you need.</h2>{items.map(item=><div key={item.title}><h3>{item.title}</h3><p>{item.body}</p></div>)}</section>}

