import Link from '@/components/navigation-link';
import {auditForService} from '@/lib/audit-tools';
import styles from './service-audit-option.module.css';
export function ServiceAuditOption({slug}:{slug:string}){const audit=auditForService(slug);return <section className={styles.option}><div><span>CHECK BEFORE YOU PLAN</span><h2>Start with an audit.</h2><p>Review the relevant website signals or supply account evidence in the tool. Use the findings to choose the work you need.</p></div><Link className="button" href={audit.href+'?service='+encodeURIComponent(slug)}>{audit.label} →</Link></section>}
const sections:Record<string,{title:string;body:string}[]>={
 'google-ads-management':[{title:'Google Ads audit',body:'Review account evidence, search terms, campaign settings, budget use and conversion measurement. Choose an audit-only scope if you want priorities before ongoing work.'},{title:'Campaign setup and ongoing management',body:'Build or improve campaigns, refine ad messages and queries, and review useful inquiries. Advertising spend and the management fee are agreed separately.'}],
 'local-seo':[{title:'Local website and search optimization',body:'Align genuine service areas, useful local pages and consistent business details with customer searches.'},{title:'Google Business Profile optimization',body:'Review eligibility, categories, services, approved photos, contact links and review response processes. This can be booked as a focused scope.'}],
 'conversion-optimization':[{title:'Conversion rate optimization',body:'Review the offer, customer questions, mobile experience and inquiry steps. Prioritize changes and a test plan based on available visitor evidence.'},{title:'GA4 and conversion tracking setup',body:'Define useful events, configure agreed tags and test successful submissions. Document what is measured and distinguish real completions from button clicks.'}],
 'social-profile-setup':[{title:'Instagram profile and search copy',body:'Review approved profile names, biographies, relevant service terms, contact links and useful content topics.'},{title:'Facebook page optimization',body:'Review business information, services, descriptions, contact actions and consistent content.'},{title:'YouTube SEO',body:'Review channel information, video titles, descriptions and useful viewer actions around the intended topic.'}]
};
export function ServiceScopes({slug}:{slug:string}){const items=sections[slug];if(!items)return null;return <section className="content-section"><h2>Choose the scope you need.</h2>{items.map(item=><div key={item.title}><h3>{item.title}</h3><p>{item.body}</p></div>)}</section>}
