'use client';
import {useEffect,useRef,useState} from 'react';
import type {CrawlItem,CrawlRow} from '@/lib/audit-crawl';
export function SiteCrawlReport({url}:{url:string}){
 const [rows,setRows]=useState<CrawlRow[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[pending,setPending]=useState(0),[count,setCount]=useState(0),[filter,setFilter]=useState('All');
 const job=useRef({queue:[] as CrawlItem[],seen:new Set<string>(),rows:[] as CrawlRow[],count:0,started:false,limited:false}),controller=useRef<AbortController|null>(null),running=useRef(false);
 useEffect(()=>()=>{running.current=false;controller.current?.abort()},[]);
 async function request(body:object){const r=await fetch('/api/audit/crawl',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,...body}),signal:controller.current?.signal});const data=await r.json() as {error?:string;items:CrawlItem[];rows:CrawlRow[];discoveryLimited?:boolean};if(!r.ok)throw Error(data.error||'Crawl unavailable');return data}
 async function start(){if(running.current)return;running.current=true;setBusy(true);setMessage('Discovering sitemap and internal links…');controller.current=new AbortController();const j=job.current;const enqueue=(items:CrawlItem[])=>{for(const item of items){const key=item.kind+':'+item.url;if(j.seen.has(key))continue;if(j.seen.size>=20000){j.limited=true;break}j.seen.add(key);j.queue.push(item)}};let batch:CrawlItem[]=[];try{if(!j.started){const seed=await request({start:true});enqueue(seed.items);j.started=true}let processed=0;while(running.current&&j.queue.length&&processed<2000){batch=j.queue.splice(0,3);const data=await request({items:batch});const blocked=data.rows?.find((r:CrawlRow)=>r.status===429||r.status===503);if(blocked){const index=batch.findIndex(i=>i.url===blocked.url);j.queue.unshift(...batch.slice(index+1))}enqueue(data.items||[]);j.rows.push(...(data.rows||[]));j.count+=batch.length-(blocked?batch.length-batch.findIndex(i=>i.url===blocked.url)-1:0);processed+=batch.length;batch=[];j.limited||=!!data.discoveryLimited;setRows([...j.rows]);setCount(j.count);setPending(j.queue.length);setMessage('Checking discovered URLs…');if(blocked){setMessage('Paused: the website returned '+blocked.status+'. Retry later to avoid overloading it.');running.current=false;break}await new Promise(r=>setTimeout(r,350))}if(running.current)setMessage(j.queue.length?'Paused at 2,000 documents this run. Continue to check remaining URLs.':j.limited?'Discovered queue checked; excerpts or discovery limits prevent a complete coverage claim.':'Discovery queue processed. Review blocked and unavailable URLs; unlisted or JavaScript-only pages may remain.');}catch(e){if(batch.length)j.queue.unshift(...batch);setMessage((e as Error).name==='AbortError'?'Crawl paused. Continue when ready.':(e as Error).message)}finally{running.current=false;setBusy(false);setPending(j.queue.length)}}
 function stop(){running.current=false;controller.current?.abort()}
 function download(){const safe=(v:unknown)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const columns=['url','status','result','finalUrl','source','title','description','detail'] as const;const csv=[columns.join(','),...rows.map(row=>columns.map(k=>safe(row[k])).join(','))].join('\r\n');const href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=href;a.download='dmb-site-url-audit.csv';a.click();setTimeout(()=>URL.revokeObjectURL(href),1000)}
 const groups=['All','404 not found','Possible soft 404','5xx server error','Redirect','Other 4xx','Robots blocked','Unavailable'];const visible=rows.filter(r=>filter==='All'||r.result===filter);
 return <section className="site-crawl"><span className="eyebrow">Website URL health</span><h3>Find broken and error pages.</h3><p>Discover public pages from XML sitemaps and internal links. Check HTTP responses, redirect destinations and possible soft 404 signals.</p><div className="crawl-actions"><button type="button" className="button" disabled={busy} onClick={start}>{job.current.started?'Continue URL crawl':'Start website URL crawl'}</button>{busy&&<button type="button" className="button button-outline" onClick={stop}>Pause crawl</button>}{rows.length>0&&<button type="button" className="button button-outline" onClick={download}>Download URL report</button>}</div><p role="status" aria-live="polite">{message}</p>{job.current.started&&<><div className="crawl-stats">{[['Documents checked',count],['URLs pending',pending],['404 / 410',rows.filter(r=>r.status===404||r.status===410).length],['Possible soft 404',rows.filter(r=>r.result==='Possible soft 404').length],['5xx',rows.filter(r=>(r.status??0)>=500).length]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="expert-filters">{groups.map(g=><button type="button" key={g} aria-pressed={filter===g} onClick={()=>setFilter(g)}>{g}</button>)}</div><div className="expert-table-scroll"><table><thead><tr><th>URL / discovery source</th><th>HTTP</th><th>Finding</th></tr></thead><tbody>{visible.slice(0,300).map((row,index)=><tr key={row.url+index}><td><a href={row.url} target="_blank" rel="noopener noreferrer">{row.url}</a><small>Found in: {row.source}</small>{row.redirects>0&&<small>Final: {row.finalUrl}</small>}</td><td>{row.status??'No response'}</td><td><strong>{row.result}</strong><small>{row.detail}</small>{row.title&&<small>Title: {row.title}</small>}</td></tr>)}</tbody></table></div>{visible.length>300&&<p>Showing 300 rows. Download the CSV for every checked URL.</p>}</>}<p className="audit-limits">Same origin only; query URLs, compressed sitemaps and common action/file URLs are excluded. Crawler rules are respected. Keep this report open while running. Soft 404 is a heuristic, not a Search Console verdict. Sitemap children are fetched; orphan pages need a sitemap or another discovery source.</p></section>
}
