'use client';
import {useState} from 'react';
import {HeroAudit} from './hero-audit';
import styles from './audit-tool-workspaces.module.css';
type Platform='instagram'|'facebook'|'youtube';
type Finding={name:string;status:'Passed'|'Review'|'Not checked';detail:string};
export function SocialAuditWorkspace(){
 const [platform,setPlatform]=useState<Platform>('instagram');const [profile,setProfile]=useState('');const [copy,setCopy]=useState('');const [keywords,setKeywords]=useState('');const [contact,setContact]=useState('');const [title,setTitle]=useState('');const [findings,setFindings]=useState<Finding[]|null>(null);
 function analyze(e:React.FormEvent){e.preventDefault();const output:Finding[]=[];let valid=false;try{const u=new URL(profile);const hosts=platform==='instagram'?['instagram.com']:platform==='facebook'?['facebook.com']:['youtube.com'];valid=u.protocol==='https:'&&hosts.some(h=>u.hostname===h||u.hostname==='www.'+h)&&u.pathname!=='/'}catch{}output.push({name:'Profile URL',status:valid?'Passed':'Review',detail:valid?'An HTTPS profile URL on the selected platform was supplied. Ownership and live availability have not been verified.':'Enter a full HTTPS profile or channel URL on the selected platform.'});
 const terms=keywords.split(',').map(k=>k.trim().toLowerCase()).filter(Boolean).slice(0,8);
 output.push({name:'Profile description',status:copy.trim()?'Passed':'Not checked',detail:copy.trim()?'Description text was supplied for review. Check that it clearly explains your services, audience and next step.':'Add your current biography or channel description to review it.'});
 const found=terms.filter(term=>copy.toLowerCase().includes(term));output.push({name:'Service keyword coverage',status:!terms.length||!copy.trim()?'Not checked':found.length===terms.length?'Passed':'Review',detail:!terms.length?'Add the service terms you want people to recognize.':!copy.trim()?'Description text is needed to check keyword coverage.':found.length===terms.length?'All supplied terms appear in the description. Keep them natural and useful.':'Terms not found in the description: '+terms.filter(t=>!found.includes(t)).join(', ')+'. Add relevant terms only where they help visitors.'});
 let contactValid=false;try{const u=new URL(contact);contactValid=['https:','mailto:','tel:'].includes(u.protocol)}catch{}
 output.push({name:'Contact or website link',status:!contact.trim()?'Not checked':contactValid?'Passed':'Review',detail:!contact.trim()?'Supply the contact link published on your profile.':contactValid?'A supported link format was supplied. Use the website scan below to review the destination; this check does not verify it is live.':'Use an HTTPS website, mailto email link or tel phone link.'});
 if(platform==='youtube')output.push({name:'Video title topic',status:!title.trim()||!terms.length?'Not checked':terms.some(t=>title.toLowerCase().includes(t))?'Passed':'Review',detail:!title.trim()?'Add a video title to review its topic wording.':!terms.length?'Add the topic keywords to compare with the title.':terms.some(t=>title.toLowerCase().includes(t))?'The title includes a supplied topic term. Review accuracy and clarity for the intended viewer.':'No supplied topic term appears in this title. Review how clearly it describes the video.'});
 setFindings(output)}
 return <><div className={styles.tabs} aria-label="Social platform">{(['instagram','facebook','youtube'] as const).map(p=><button key={p} aria-pressed={platform===p} onClick={()=>{setPlatform(p);setFindings(null)}}>{p==='youtube'?'YouTube':p[0].toUpperCase()+p.slice(1)}</button>)}</div><section className={styles.panel}><h2>Review your profile and search copy</h2><p>Paste your published information for a focused optimization check. This reviews the information you supply; it does not fetch private insights or verify follower and engagement figures.</p><form onSubmit={analyze} className={styles.profileForm}><label>Profile or channel URL<input type="url" required value={profile} maxLength={2000} placeholder={'https://www.'+platform+'.com/your-profile'} onChange={e=>setProfile(e.target.value)}/></label><label>Service or topic keywords, separated by commas<input value={keywords} maxLength={300} placeholder="Your services and customer topics" onChange={e=>setKeywords(e.target.value)}/></label><label>Current bio, page or channel description<textarea value={copy} maxLength={6000} rows={4} onChange={e=>setCopy(e.target.value)}/></label><label>Published website or contact link<input value={contact} maxLength={2000} placeholder="https://yourwebsite.com" onChange={e=>setContact(e.target.value)}/></label>{platform==='youtube'&&<label>Video title to review<input value={title} maxLength={200} onChange={e=>setTitle(e.target.value)}/></label>}<button className="button" type="submit">Analyze profile copy</button></form>{findings&&<div className={styles.findings} aria-live="polite"><h3>Your profile optimization review</h3>{findings.map(f=><article key={f.name}><h4>{f.name}<span>{f.status}</span></h4><p>{f.detail}</p></article>)}</div>}</section><h2 className={styles.scanHeading}>Check your website’s social signals</h2><HeroAudit fullPage auditKind="social"/></>
}
