export type AuditKind='all'|'seo'|'ads'|'social'|'local';
export const auditTools=[
 {kind:'seo',slug:'seo-audit',href:'/seo-bureau#service-audit',name:'SEO Audit Tool',title:'SEO Audit & Website Health Tool',description:'Check search visibility, metadata, headings, content, schema, discovery files and page performance.',meta:'Run a free SEO audit for metadata, headings, schema, crawl discovery and website performance. Review evidence and prioritized fixes.'},
 {kind:'local',slug:'local-seo-audit',href:'/seo-bureau#local-seo',name:'Local SEO & GBP Tool',title:'Local SEO & Google Business Profile Audit',description:'Find a business listing by name and city, review its public details and audit the local website.',meta:'Review local website SEO and Google Business Profile details. Search business suggestions when Google Places is connected.'},
 {kind:'ads',slug:'ads-audit',href:'/services/google-ads-management#service-audit',name:'Ads Audit & Optimization Tool',title:'Google, Meta & LinkedIn Ads Audit & Optimization',description:'Review landing-page readiness and tracking, or analyze an authorized campaign CSV export.',meta:'Audit Google Ads, Meta Ads and LinkedIn Ads. Review website tracking and landing pages, or analyze your campaign CSV export.'},
 {kind:'social',slug:'social-media-audit',href:'/services/social-media-content-management#service-audit',name:'Social Media Audit Tool',title:'Instagram, Facebook & YouTube Audit',description:'Review profile information, service keywords, video copy, contact links and website sharing signals.',meta:'Review Instagram, Facebook and YouTube profile copy, search keywords and contact paths, plus your website social sharing and profile links.'}
] as const;
export function auditForService(slug:string){if(slug==='seo-bureau')return {href:'/seo-bureau#service-audit',label:'Run a local SEO and GBP audit'};if(/social|reputation/.test(slug)&&slug!=='paid-social-advertising')return {href:'/services/social-media-content-management#service-audit',label:'Run a social media audit'};if(/ads|advertising|paid|retarget/.test(slug))return {href:'/services/google-ads-management#service-audit',label:'Run an ads audit'};if(/seo|search|content/.test(slug))return {href:'/seo-bureau#service-audit',label:'Run an SEO audit'};return {href:'/dmb-audit',label:'Run a website marketing audit'};}

