import {businessSignals} from './audit-business';
import {analysePage,type AuditCheck} from './audit';
export type ExpertCheck=AuditCheck&{category:string;priority:'High'|'Medium'|'Low';status:'passed'|'review'|'unavailable'};
export type DiscoveryFile={status:number|null;body:string;url?:string};
export type DiscoveryResult={robots:DiscoveryFile;sitemap:DiscoveryFile;llms?:DiscoveryFile};
export function expertReport(html:string,url:string,headers:Headers,discovery?:DiscoveryResult){
 const raw=html.replace(/<!--[\s\S]*?-->/g,'');const markup=raw.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi,' ');
 const schemas=[...raw.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi)].map(m=>m[0]).join('');const base=analysePage(markup+schemas,url);const clean=(v:string)=>v.replace(/<[^>]+>/g,' ').replace(/&(?:nbsp|amp|quot|#39);/g,' ').replace(/\s+/g,' ').trim();
 const attrs=(tag:string)=>Object.fromEntries([...tag.matchAll(/([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g)].map(m=>[m[1].toLowerCase(),m[2]??m[3]??m[4]??'']));
 const tags=(name:string)=>[...markup.matchAll(new RegExp('<'+name+'\\b[^>]*>','gi'))].map(m=>attrs(m[0]));const meta=tags('meta'),images=tags('img'),anchors:Array<Record<string,string>>=[...markup.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)].map(m=>({...attrs(m[1]),text:clean(m[2])}));
 const page=new URL(url),headings=[...markup.matchAll(/<h([1-6])\b[^>]*>([\s\S]*?)<\/h\1>/gi)].map(m=>({level:Number(m[1]),text:clean(m[2])}));const get=(key:string)=>meta.find(m=>(m.name||m.property||'').toLowerCase()===key)?.content||'';
 const categories:Record<string,string>={https:'Security',title:'On-page SEO',description:'On-page SEO',h1:'Content',viewport:'Usability',canonical:'On-page SEO',social:'Social',language:'Usability',alt:'Images',schema:'On-page SEO',content:'Content'};
 const checks:ExpertCheck[]=base.checks.map(c=>({...c,category:categories[c.id],priority:['h1','title'].includes(c.id)?'High':'Medium',status:c.passed?'passed':'review'}));
 function add(id:string,name:string,category:string,passed:boolean,detail:string,fix:string,priority:'High'|'Medium'|'Low'='Medium',unavailable=false){checks.push({id,name,category,passed,detail,fix,priority,status:unavailable?'unavailable':passed?'passed':'review'})}
 const index= [get('robots'),get('googlebot'),headers.get('x-robots-tag')||''].join(',');
 add('indexability','Indexing directives','On-page SEO',!/\bnoindex\b|\bnone\b/i.test(index),index||'No noindex directive found in returned metadata or response headers.','If this page should appear in search, review its noindex directive. This does not confirm Google indexing.','High');
 add('title-length','Title length review','On-page SEO',base.title.length>=15&&base.title.length<=65,base.title.length+' characters. Character ranges are editorial guidance, not Google limits.','Make the title specific and concise; review how it appears in search.');
 add('description-length','Description length review','On-page SEO',base.description.length>=50&&base.description.length<=160,base.description.length+' characters. Search engines may choose a different snippet.','Explain the offer and next step clearly without repeated wording.','Low');
 const canon=tags('link').find(t=>t.rel?.split(/\s+/).includes('canonical'))?.href;let same=false;try{same=!!canon&&new URL(canon,page).origin===page.origin}catch{}
 add('canonical-origin','Canonical destination','On-page SEO',same,canon||'No canonical destination found.','Review whether the canonical intentionally points to this website or an external source.');
 let previous=0,skips=0;for(const h of headings){if(previous&&h.level>previous+1)skips++;previous=h.level}
 add('heading-order','Heading structure','Content',skips===0,headings.length+' headings; '+skips+' level jumps.','Use headings that reflect the structure of the page; review skipped levels.','Low');
 add('empty-headings','Empty headings','Content',headings.every(h=>h.text),headings.filter(h=>!h.text).length+' empty headings found.','Give each meaningful heading clear text.');
 const meaningful=images.filter(i=>i.alt?.trim()),empty=images.filter(i=>Object.hasOwn(i,'alt')&&!i.alt?.trim());
 add('image-dimensions','Image layout dimensions','Images',images.every(i=>(i.width&&i.height)||/aspect-ratio/.test(i.style||'')),images.filter(i=>!(i.width&&i.height)&&!/aspect-ratio/.test(i.style||'')).length+' images without HTML dimensions or inline aspect ratio. CSS may provide dimensions.','Reserve image space with dimensions or CSS aspect-ratio to reduce layout movement.');
 add('responsive-images','Responsive image sources','Images',images.every(i=>i.srcset||/^data:|\.svg(?:\?|$)/i.test(i.src||'')),images.filter(i=>i.srcset).length+' of '+images.length+' images declare srcset. This does not measure their file sizes.','Use appropriately sized image sources; single-source logos may already be suitable.','Low');
 const brokenLinks=anchors.filter(a=>!a.href||a.href==='#'||/^javascript:/i.test(a.href));
 add('placeholder-links','Placeholder navigation links','Links',brokenLinks.length===0,brokenLinks.length+' links have missing, placeholder or JavaScript-only destinations.','Give navigation links a working destination; use buttons for actions.');
 const internal:string[]=[],external:string[]=[];for(const a of anchors){try{if(!a.href||/^(mailto:|tel:|#)/i.test(a.href))continue;const dest=new URL(a.href,page);if(!['http:','https:'].includes(dest.protocol))continue;(dest.origin===page.origin?internal:external).push(dest.toString())}catch{}}
 add('internal-links','Internal discovery links','Links',internal.length>0,internal.length+' internal links to '+new Set(internal).size+' distinct URLs. Destinations have not been crawled.','Link related services, useful guides and important pages together.');
 add('link-labels','Accessible link labels','Usability',anchors.every(a=>a.text||a['aria-label']||a.title||/img|svg/i.test(a.href||'')),anchors.filter(a=>!a.text&&!a['aria-label']&&!a.title).length+' links need an accessible-name review. Nested images or icons may supply a name.','Check the accessible name of icon links in a browser.','Low');
 add('og-image','Social sharing image','Social',!!get('og:image'),get('og:image')||'No Open Graph image declared.','Add a relevant absolute sharing-image URL and test the social preview.');
 add('twitter-card','Twitter / X card','Social',!!get('twitter:card'),get('twitter:card')||'No Twitter card type found.','Declare a suitable Twitter card and sharing image.','Low');
 add('social-profiles','Public social profile links','Social',anchors.some(a=>/linkedin\.com|facebook\.com|instagram\.com|x\.com|twitter\.com/i.test(a.href||'')),'Checks for links to major social networks in the returned HTML. Ownership and profile quality are not verified.','Link your genuine business profiles where useful.','Low');
 const insecure=[...tags('img'),...tags('script'),...tags('link')].filter(t=>/^http:/i.test(t.src||t.href||''));
 add('mixed-content','Insecure resource references','Security',page.protocol!=='https:'||insecure.length===0,insecure.length+' HTTP resource references found in markup. Browser behaviour not tested.','Serve resources over HTTPS and check the browser console.');
 for(const [id,name,header,fix] of [['hsts','HTTPS policy header','strict-transport-security','Review HSTS after confirming HTTPS works across the intended hosts.'],['csp','Content security policy','content-security-policy','Review a suitable content security policy for your application.'],['mime-protection','Content-type protection','x-content-type-options','Consider the nosniff response header.'],['referrer-policy','Referrer policy','referrer-policy','Choose a suitable referrer policy.']])add(id,name,'Security',!!headers.get(header),headers.get(header)||'Header not present in this response.',fix,'Low');
 add('contact-path','Contact options','Usability',anchors.some(a=>/^(mailto:|tel:)/i.test(a.href||'')||/contact|enquir|book/i.test(a.href||'')),'Checks for a contact, enquiry, phone or email destination. Delivery and form submissions are not tested.','Give visitors a clear way to contact the business.');
 add('privacy-link','Privacy information link','Usability',anchors.some(a=>/privacy/i.test(a.href||'')),'Checks for a privacy link; legal adequacy is not assessed.','Make the relevant privacy information easy to find.','Low');
 const robots=discovery?.robots,sitemap=discovery?.sitemap;
 add('robots-file','robots.txt availability','Discovery',robots?.status===200&&/^\s*User-agent\s*:/im.test(robots.body)&&!/<html\b/i.test(robots.body),robots?.status===null||!robots?'Could not retrieve robots.txt.':'robots.txt returned HTTP '+robots.status+'.','Review the public robots.txt file and crawler rules.','Medium',!robots||robots.status===null);
 add('sitemap-file','XML sitemap discovery','Discovery',sitemap?.status===200&&/<(?:[\w-]+:)?(?:urlset|sitemapindex)\b/i.test(sitemap.body),sitemap?.status===null||!sitemap?'Could not retrieve the declared same-origin sitemap or /sitemap.xml.':'Sitemap endpoint returned HTTP '+sitemap.status+'.','Publish an XML sitemap with canonical, indexable URLs and declare it in robots.txt.','Medium',!sitemap||sitemap.status===null);


 const metadata=[{name:'Title',value:base.title,count:[...markup.matchAll(/<title\b[^>]*>/gi)].length},...['description','robots','googlebot','bingbot','viewport','keywords','og:title','og:description','og:image','og:url','og:type','og:locale','twitter:card','twitter:title','twitter:description','twitter:image'].map(name=>({name,value:get(name),count:meta.filter(m=>(m.name||m.property||'').toLowerCase()===name).length})),{name:'Canonical',value:canon||'',count:tags('link').filter(t=>t.rel?.toLowerCase().split(/\s+/).includes('canonical')).length},{name:'X-Robots-Tag',value:headers.get('x-robots-tag')||'',count:headers.has('x-robots-tag')?1:0}];
 add('duplicate-metadata','Duplicate primary metadata','On-page SEO',metadata.filter(m=>['Title','description','Canonical'].includes(m.name)).every(m=>m.count<=1),metadata.filter(m=>m.count>1).map(m=>m.name+': '+m.count+' declarations').join('; ')||'No duplicate primary declarations found.','Keep one intentional title, meta description and canonical per page.');
 for(const key of ['og:title','og:description','og:url','og:type','twitter:title','twitter:description','twitter:image'])add('meta-'+key.replace(':','-'),key+' metadata','Social',!!get(key),get(key)||'Not declared in returned HTML.','Review social previews and add relevant sharing metadata. Platforms may use fallback values.','Low');
 const notHTML=(body:string)=>!/<(?:!doctype|html|head|body)\b/i.test(body);
 const fileDetails=([
 {name:'robots.txt',data:robots,url:new URL('/robots.txt',page).href,valid:(body:string)=>notHTML(body)&&/^\s*User-agent\s*:/im.test(body),note:'Crawler rules, not proof of indexing.'},
 {name:'XML sitemap',data:sitemap,url:new URL('/sitemap.xml',page).href,valid:(body:string)=>notHTML(body)&&/<(?:[\w-]+:)?(?:urlset|sitemapindex)\b/i.test(body),note:'Root sitemap only; linked sitemap files and their URLs have not been crawled.'},
 {name:'llms.txt',data:discovery?.llms,url:new URL('/llms.txt',page).href,valid:(body:string)=>notHTML(body)&&/^#\s+\S/m.test(body),note:'Optional Markdown resource guide. Not a ranking requirement or crawler permission file.'}
 ]).map(f=>{const data=f.data,valid=!!data&&data.status===200&&f.valid(data.body);const status=!data||data.status===null?'Unavailable':data.status===404||data.status===410?'Not found':valid?'Available':data.status===200?'Format review':'HTTP '+data.status;return {name:f.name,url:data?.url||f.url,httpStatus:data?.status??null,status,valid,note:f.note,preview:data?.status===200?data.body.slice(0,3500):'',entries:f.name==='XML sitemap'?(data?.body.match(/<(?:[\w-]+:)?loc\b[^>]*>/gi)||[]).length:null}});
 const robotRules=robots?.status===200?robots.body.split(/\r?\n/).filter(line=>/^\s*(user-agent|allow|disallow|sitemap)\s*:/i.test(line)).slice(0,60):[];
 const llmsLinks=discovery?.llms?.status===200?(discovery.llms.body.match(/\[[^\]]+\]\([^)]+\)/g)||[]).length:0;
 const available=checks.filter(c=>c.status!=='unavailable'),passed=available.filter(c=>c.passed).length;
 const groups=[...new Set(checks.map(c=>c.category))].map(name=>{const all=checks.filter(c=>c.category===name),measured=all.filter(c=>c.status!=='unavailable');return {name,passed:measured.filter(c=>c.passed).length,total:measured.length,unavailable:all.length-measured.length,score:measured.length?Math.round(measured.filter(c=>c.passed).length/measured.length*100):null}});
 return {...base,business:businessSignals(html,url),metadata,files:fileDetails,robotRules,llmsLinks,checks,groups,passed,total:available.length,score:Math.round(passed/available.length*100),scope:'Submitted page HTML, response headers and root discovery files. Not a full-site crawl, ranking prediction, accessibility certification or security assessment.',facts:{title:base.title,description:base.description,wordCount:base.wordCount,headings:headings.slice(0,35),images:images.length,missingAlt:images.filter(i=>!Object.hasOwn(i,'alt')).length,emptyAlt:empty.length,describedImages:meaningful.length,internalLinks:internal.length,externalLinks:external.length,htmlBytes:new TextEncoder().encode(html).length},priorities:checks.filter(c=>c.status==='review').sort((a,b)=>['High','Medium','Low'].indexOf(a.priority)-['High','Medium','Low'].indexOf(b.priority)).slice(0,8)};
}
