export type AuditCheck={id:string;name:string;passed:boolean;detail:string;fix:string};
export function analysePage(html:string,url:string){
 const clean=(s:string)=>s.replace(/<[^>]*>/g,' ').replace(/&(?:nbsp|amp|quot|#39);/g,' ').replace(/\s+/g,' ').trim();
 const attrs=(tag:string)=>Object.fromEntries([...tag.matchAll(/([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g)].map(m=>[m[1].toLowerCase(),m[2]??m[3]??m[4]??'']));
 const meta=[...html.matchAll(/<meta\b[^>]*>/gi)].map(m=>attrs(m[0]));const links=[...html.matchAll(/<link\b[^>]*>/gi)].map(m=>attrs(m[0]));
 const title=clean(html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'');const description=meta.find(m=>m.name?.toLowerCase()==='description')?.content?.trim()||'';
 const headings=[...html.matchAll(/<h1\b[^>]*>([\s\S]*?)<\/h1>/gi)].map(m=>clean(m[1]));const imageAttrs=[...html.matchAll(/<img\b[^>]*>/gi)].map(m=>attrs(m[0]));const missingAlt=imageAttrs.filter(i=>!Object.hasOwn(i,'alt')).length;
 const canonical=links.find(l=>l.rel?.toLowerCase().split(/\s+/).includes('canonical'))?.href||'';let canonicalValid=false;try{const parsed=new URL(canonical);canonicalValid=['https:','http:'].includes(parsed.protocol)}catch{}
 const lang=attrs(html.match(/<html\b[^>]*>/i)?.[0]||'').lang||'';const viewport=meta.find(m=>m.name?.toLowerCase()==='viewport')?.content||'';
 const ogTitle=meta.find(m=>m.property?.toLowerCase()==='og:title')?.content||'';const ogDescription=meta.find(m=>m.property?.toLowerCase()==='og:description')?.content||'';
 const scripts=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)].filter(m=>attrs(m[1]).type?.toLowerCase()==='application/ld+json');let validSchema=false;for(const s of scripts){try{const data=JSON.parse(s[2]);const items=Array.isArray(data)?data:[data];validSchema||=items.some(x=>x&&typeof x==='object'&&x['@context']&&((x['@type'])||Array.isArray(x['@graph'])))}catch{}}
 const text=clean(html.replace(/<(script|style|nav|header|footer)\b[^>]*>[\s\S]*?<\/\1>/gi,' '));const wordCount=text.split(/\s+/).filter(Boolean).length;
 const check=(id:string,name:string,passed:boolean,detail:string,fix:string):AuditCheck=>({id,name,passed,detail,fix});
 const checks=[check('https','HTTPS',new URL(url).protocol==='https:','Final page uses '+new URL(url).protocol.replace(':','').toUpperCase()+'.','Use HTTPS and redirect the HTTP version to the secure URL.'),check('title','Page title',title.length>0,title?title:'No non-empty title found.','Add a descriptive title that reflects the page’s offer.'),check('description','Meta description',description.length>0,description||'No non-empty meta description found.','Write a clear description of the page and its useful next step.'),check('h1','Primary heading',headings.length===1&&headings[0].length>0,headings.length+' H1 heading(s) found.','Use one clear primary heading for this page.'),check('viewport','Mobile viewport',/width\s*=\s*device-width/i.test(viewport),viewport||'No viewport meta tag found.','Set a device-width viewport and check the actual mobile layout.'),check('canonical','Canonical URL',canonicalValid,canonical||'No canonical URL found.','Declare the intended canonical page using an absolute URL.'),check('social','Social preview tags',Boolean(ogTitle&&ogDescription),'Open Graph title '+(ogTitle?'present':'missing')+'; description '+(ogDescription?'present':'missing')+'.','Add accurate Open Graph title and description tags.'),check('language','Page language',Boolean(lang),lang?'Declared language: '+lang:'No HTML language attribute found.','Declare the actual page language in the HTML lang attribute.'),check('alt','Image alt attributes',missingAlt===0,imageAttrs.length+' image(s); '+missingAlt+' missing an alt attribute.','Give meaningful images descriptive alt text; decorative images can use an empty alt attribute.'),check('schema','Structured data',validSchema,validSchema?'Parseable JSON-LD with a context and type or graph found.':'No qualifying parseable JSON-LD found.','Add relevant, accurate structured data and validate it with the appropriate testing tool.'),check('content','Server-readable content',wordCount>=100,wordCount+' approximate words in the returned HTML, excluding common navigation blocks.','Check that the response contains useful page content. Short copy or JavaScript rendering may need manual review.')];
 const passed=checks.filter(c=>c.passed).length;return {url,title,description,checks,passed,total:checks.length,score:Math.round(passed/checks.length*100),wordCount};
}
export function validatePublicUrl(input:string){const value=/^https?:\/\//i.test(input)?input:'https://'+input;let url:URL;try{url=new URL(value)}catch{throw new Error('Enter a valid public website address.')}const host=url.hostname.toLowerCase();if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.port||host.length>253||!host.includes('.')||/[^a-z0-9.-]/.test(host)||/^\d+(\.\d+){3}$/.test(host)||host==='localhost'||host.endsWith('.localhost')||host.endsWith('.local')||host.endsWith('.internal')||host.endsWith('.test')||host.endsWith('.lan')||host==='metadata.google.internal')throw new Error('Use a public website domain without a custom port or login details.');url.hash='';return url}
export function isPublicAddress(ip:string){if(ip.includes(':')){const v=ip.toLowerCase();return !v.startsWith('::')&&!v.startsWith('fc')&&!v.startsWith('fd')&&!v.startsWith('fe8')&&!v.startsWith('fe9')&&!v.startsWith('fea')&&!v.startsWith('feb')&&!v.startsWith('ff')&&!v.startsWith('2001:db8');}const p=ip.split('.').map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))return false;const [a,b]=p;return !(a===0||a===10||a===127||a>=224||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&(b===168||b===0))||(a===100&&b>=64&&b<=127)||(a===198&&(b===18||b===19||b===51))||(a===203&&b===0));}
