import {IndustryTicker} from '@/components/industry-ticker';
import Link from '@/components/navigation-link';
import { notFound } from 'next/navigation';
import { ArrowUpRight } from 'lucide-react';
import { markets } from '@/lib/markets';
import { services,industries } from '@/lib/content';
import { Breadcrumb, CTA, CheckList, SectionTitle, ServiceCard, Schema } from '@/components/blocks';
import { pageMeta,origin } from '@/lib/site';
export function generateStaticParams(){return markets.map(m=>({slug:m.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const m=markets.find(m=>m.slug===slug);return m?pageMeta('SEO & Performance Marketing for '+m.name,m.summary,'/markets/'+slug):{title:'Market not found'}}
export default async function MarketPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const m=markets.find(m=>m.slug===slug);if(!m)notFound();return <main id="main"><section className="page-intro"><Breadcrumb items={[{label:'Markets',href:'/markets'},{label:m.name}]}/><span className="eyebrow">Market focus / {m.short}</span><h1>{m.headline}</h1><p>{m.summary}</p><Link href={'/contact?market='+encodeURIComponent(m.name)} className="button">Request a plan for {m.short} <ArrowUpRight size={20}/></Link></section><section className="section industry-context"><div><span className="eyebrow">Market context</span><h2>Reach customers<br/>in the areas you serve.</h2></div><div><p className="lead-paragraph">{m.context}</p><CheckList items={m.priorities}/></div></section><section className="section related-section"><SectionTitle kicker="Services that may help" title={'A starting point for '+m.short+' businesses.'}/><div className="service-grid">{m.serviceSlugs.map(sl=>services.find(s=>s.slug===sl)).map(s=><ServiceCard key={s!.slug} service={s!}/>)}</div></section><section className="section industry-method"><div><span className="eyebrow">A practical approach</span><h2>Plan around your customers and location.</h2><p>{m.approach}</p></div><div className="measurement-panel"><span className="eyebrow">Working across borders</span><h3>How we work with your team.</h3><p>{m.coordination}</p></div></section><section className="section"><SectionTitle kicker="Your type of business" title="Find services for your business type."/><IndustryTicker items={industries.map(({slug,name})=>({slug,name}))}/></section><section className="section"><div className="faq-list"><details><summary>{m.faq}<span>+</span></summary><p>{m.answer}</p></details><details><summary>How do I get a quote?<span>+</span></summary><p>Share your website, customer locations and goals. We recommend the relevant work and confirm scope, timing and fees. Example packages are available, with final pricing agreed for your requirements.</p></details></div></section><section className="section"><SectionTitle kicker="Across markets" title="Explore another market."/><div className="crosslink-grid">{markets.filter(x=>x.slug!==slug).map(x=><Link href={'/markets/'+x.slug} key={x.slug}>{x.name}<ArrowUpRight size={20}/></Link>)}</div></section><CTA/><Schema data={{'@context':'https://schema.org','@type':'Service',name:'SEO & Performance Marketing for '+m.name,description:m.summary,url:origin+'/markets/'+slug,areaServed:{'@type':slug==='dubai'?'City':'Country',name:m.name},provider:{'@id':origin+'/#organization'}}}/></main>}
