import {fetchAuditPage} from '@/lib/audit-public-fetch';
import {validatePublicUrl,isPublicAddress} from '@/lib/audit';
import {crawlUrl,robotsAllowed,crawlSignals,sitemapItems,type CrawlItem,type CrawlRow} from '@/lib/audit-crawl';
const headers={'Cache-Control':'no-store'};
async function dns(host:string,signal:AbortSignal){const results=await Promise.all(['A','AAAA'].map(async type=>{const r=await fetch('https://cloudflare-dns.com/dns-query?name='+encodeURIComponent(host)+'&type='+type,{signal,headers:{Accept:'application/dns-json'}});if(!r.ok)throw Error('DNS lookup failed');const data=await r.json() as any;return (data.Answer||[]).filter((x:any)=>x.type===1||x.type===28).map((x:any)=>x.data)}));if(!results.flat().length||results.flat().some(ip=>!isPublicAddress(ip)))throw Error('Public DNS required')}
async function read(url:string,origin:string,rules?:string){const signal=AbortSignal.timeout(9000);let current=validatePublicUrl(url),redirects=0,initial:number|null=null;for(let hop=0;hop<=3;hop++){if(current.origin!==origin)throw Error('External redirect not followed');await dns(current.hostname,signal);const r=await fetchAuditPage(current,{redirect:'manual',signal,headers:{'User-Agent':'DMB-Website-Audit/2.0',Accept:'text/html,application/xml,text/plain'}});initial??=r.status;if([301,302,303,307,308].includes(r.status)){const location=r.headers.get('location');await r.body?.cancel();if(!location||hop===3)return {status:r.status,initial,finalUrl:current.href,body:'',type:'',redirects,truncated:false};const next=validatePublicUrl(new URL(location,current).href);if(next.origin!==origin||(rules!==undefined&&(!crawlUrl(next.href,origin)||!robotsAllowed(rules,next.pathname))))return {status:r.status,initial,finalUrl:next.href,body:'',type:'external',redirects:redirects+1,truncated:false};current=next;redirects++;continue}const reader=r.body?.getReader(),decoder=new TextDecoder();let body='',size=0,truncated=false;if(reader){for(;;){const n=await reader.read();if(n.done)break;size+=n.value.length;if(size>750000){truncated=true;await reader.cancel();break}body+=decoder.decode(n.value,{stream:true})}body+=decoder.decode()}return {status:r.status,initial,finalUrl:current.href,body,type:r.headers.get('content-type')||'',redirects,truncated}}throw Error('Redirect failed')}
export async function POST(request:Request){if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Use the audit form.'},{status:403,headers});try{const raw=await request.text();if(raw.length>18000)throw Error('Request too large');const data=JSON.parse(raw),base=validatePublicUrl(data.url),origin=base.origin;const robots=await read(origin+'/robots.txt',origin);if(robots.status>=500||robots.status===429||robots.type==='external')return Response.json({error:'Crawler rules could not be confirmed. Retry when robots.txt is reachable.'},{status:422,headers});const rules=robots.status===200?robots.body:'';
 if(data.start){const seeds:CrawlItem[]=[{url:origin+'/',kind:'page',source:'Homepage'},{url:base.href,kind:'page',source:'Submitted URL'},{url:origin+'/sitemap.xml',kind:'sitemap',source:'Default sitemap'}];for(const m of rules.matchAll(/^\s*Sitemap:\s*(\S+)/gim)){const u=crawlUrl(m[1],origin);if(u)seeds.push({url:u,kind:'sitemap',source:'robots.txt'})}return Response.json({items:seeds,rows:[],limits:'Same origin, no query URLs; public linked pages and uncompressed XML sitemaps.'},{headers})}
 if(!Array.isArray(data.items)||data.items.length>3)throw Error('Use batches of up to three URLs');const items:CrawlItem[]=[],rows:CrawlRow[]=[];let discoveryLimited=false;
 // Sequential requests avoid bursts against the audited website.
 for(const entry of data.items){const target=crawlUrl(entry.url,origin);if(!target)throw Error('Same-origin public URL required');const kind=entry.kind==='sitemap'?'sitemap':'page';const row:CrawlRow={url:target,finalUrl:target,status:null,result:'Unavailable',detail:'',source:String(entry.source||'').slice(0,2000),title:'',description:'',redirects:0,truncated:false};if(!robotsAllowed(rules,new URL(target).pathname)){row.result='Robots blocked';row.detail='Not fetched: DMB crawler rules disallow this path.';rows.push(row);continue}try{const page=await read(target,origin,rules);Object.assign(row,{finalUrl:page.finalUrl,status:page.status,redirects:page.redirects,truncated:page.truncated});discoveryLimited||=page.truncated;if(kind==='sitemap'&&page.status===200&&/<(?:[\w-]+:)?(?:urlset|sitemapindex)\b/i.test(page.body)){const found=sitemapItems(page.body,page.finalUrl);items.push(...found);discoveryLimited||=found.length>=2000;continue}row.result=page.status>=500?'5xx server error':page.status===404?'404 not found':page.status===410?'410 gone':page.status===429?'Rate limited':page.status>=400?'Other 4xx':page.status>=300?'Redirect':page.status===200?'OK':'Other response';row.detail=page.type==='external'?'External, excluded or robots-blocked redirect not followed.':page.redirects?'Redirect chain followed: '+page.redirects+' hops.':'';if(page.status===200&&/text\/html|application\/xhtml/i.test(page.type)){const signals=crawlSignals(page.body,page.finalUrl);row.title=signals.title;row.description=signals.description;if(signals.soft){row.result='Possible soft 404';row.detail='HTTP 200, but the title or H1 contains an error-page message. Manual confirmation required.'}items.push(...signals.links.map(url=>({url,kind:'page' as const,source:target})));discoveryLimited||=signals.links.length>=1000}if(kind==='sitemap'&&page.status===200){row.result='Sitemap format review';row.detail='This sitemap endpoint did not return a recognised XML sitemap.';discoveryLimited=true}if(page.truncated)row.detail+=' Response excerpt limited to 750 KB; discovery may be incomplete.'}catch(e){row.detail=e instanceof Error&&e.name==='TimeoutError'?'Timed out. No HTTP status confirmed.':'Could not retrieve this URL; no HTTP status confirmed.'}rows.push(row);if(row.status===429||row.status===503)break}
 return Response.json({rows,items:items.slice(0,2000),discoveryLimited:discoveryLimited||items.length>2000},{headers});}catch{return Response.json({error:'Crawl request could not run. Check the URL or try again.'},{status:422,headers})}}
