const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),Module=require('node:module'),ts=require('typescript');const root=process.cwd(),cache=new Map(),original=Module._load;
function load(p){if(cache.has(p))return cache.get(p).exports;const m=new Module(p,module);m.filename=p;m.paths=Module._nodeModulePaths(path.dirname(p));cache.set(p,m);m._compile(ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,p);return m.exports}
Module._load=function(name,parent){if(name.startsWith('@/'))return load(path.join(root,name.slice(2)+'.ts'));if(parent&&name.startsWith('.')){const p=path.resolve(path.dirname(parent.filename),name+'.ts');if(fs.existsSync(p))return load(p)}return original.apply(this,arguments)};
(async()=>{const {expertReport}=load(path.join(root,'lib/audit-expert.ts'));const {validatePublicUrl}=load(path.join(root,'lib/audit.ts'));const {readLighthouse}=load(path.join(root,'lib/audit-performance.ts'));const {POST}=load(path.join(root,'app/api/audit/route.ts'));
const html=`<!doctype html><html lang="en"><head><title>Useful business website title</title><meta name="description" content="A clear explanation of the business services with a useful way to contact the team."><meta name="viewport" content="width=device-width"><link rel="canonical" href="https://example.com/"></head><body><h1>Customer services</h1><h3>Details</h3><img src="test.webp"><a href="/contact">Contact</a><script>const fake='<meta name="robots" content="noindex"><h1>Fake heading</h1>';</script><script type="application/ld+json">{"@context":"https://schema.org","@type":"Organization","name":"Example"}</script></body></html>`;
let r=expertReport(html,'https://example.com/',new Headers());assert.equal(r.facts.headings.length,2);assert.equal(r.facts.missingAlt,1);assert(r.checks.find(c=>c.id==='schema').passed);assert(r.checks.find(c=>c.id==='indexability').passed);assert(!r.checks.find(c=>c.id==='heading-order').passed);assert.equal(r.checks.find(c=>c.id==='sitemap-file').status,'unavailable');assert.equal(r.total,r.checks.length-2);
r=expertReport(html,'https://example.com/',new Headers({'x-robots-tag':'noindex'}),{robots:{status:200,body:'User-agent: *'},sitemap:{status:200,body:'<html>Not a sitemap</html>'}});assert(!r.checks.find(c=>c.id==='indexability').passed);assert(!r.checks.find(c=>c.id==='sitemap-file').passed);assert.equal(r.priorities[0].priority,'High');
assert.equal(readLighthouse({lighthouseResult:{runtimeError:{code:'NO_FCP'}}}),null);assert.equal(readLighthouse({lighthouseResult:{categories:{performance:{score:.8}},audits:{}}}).score,80);
for(const value of ['http://127.0.0.1','http://localhost','http://user:password@example.com','http://example.com:8080','file:///tmp/a'])assert.throws(()=>validatePublicUrl(value));
const calls=[];global.fetch=async(input)=>{const u=String(input);calls.push(u);if(u.startsWith('https://cloudflare-dns.com'))return Response.json({Answer:[{type:1,data:'93.184.216.34'}]});if(u.endsWith('/robots.txt'))return new Response('Sitemap: https://private.example.net/sitemap.xml');if(u.endsWith('/sitemap.xml'))return new Response('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>');return new Response(html,{headers:{'content-type':'text/html'}})};
let response=await POST(new Request('https://dmbureau.cloud/api/audit',{method:'POST',headers:{origin:'https://evil.example'},body:JSON.stringify({url:'example.com'})}));assert.equal(response.status,403);
response=await POST(new Request('https://dmbureau.cloud/api/audit',{method:'POST',body:JSON.stringify({url:'example.com'})}));assert.equal(response.status,200);const data=await response.json();assert(data.groups.length>=7);assert(data.checks.length>=30);assert(!calls.some(u=>u.includes('private.example.net')));assert(data.checks.find(c=>c.id==='sitemap-file').passed);
global.fetch=async(input)=>String(input).startsWith('https://cloudflare-dns.com')?Response.json({Answer:[{type:1,data:'127.0.0.1'}]}):new Response(html);response=await POST(new Request('https://dmbureau.cloud/api/audit',{method:'POST',body:JSON.stringify({url:'example.com'})}));assert.equal(response.status,422);
console.log(JSON.stringify({checks:data.checks.length,categories:data.groups.length,htmlSignals:'script content excluded',missingData:'excluded from score',discovery:'same-origin only',safety:'private DNS and cross-origin requests blocked',lighthouse:'runtime errors do not become scores'},null,2))})().catch(e=>{console.error(e);process.exitCode=1});
