const fs=require('node:fs');const path=require('node:path');const Module=require('node:module');const assert=require('node:assert/strict');const ts=require('typescript');const React=require('react');const {renderToStaticMarkup}=require('react-dom/server');
const root=process.cwd();const originalLoad=Module._load;const cache=new Map();const records=[];let failDb=false;
function loadFile(file){if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));if(cache.has(file))return cache.get(file).exports;const m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));cache.set(file,m);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,file);return m.exports}
function resolveLocal(p){for(const f of [p,p+'.ts',p+'.tsx',path.join(p,'index.ts')])if(fs.existsSync(f)&&fs.statSync(f).isFile())return f;return null}
Module._load=function(request,parent,isMain){if(request.endsWith('.css'))return {__esModule:true,default:new Proxy({},{get:(_,key)=>String(key)})};if(request.endsWith('.jpg?url'))return {__esModule:true,default:'/images/'+path.basename(request).replace('?url','')};if(request==='next/link')return {__esModule:true,default:({href,children,...rest})=>React.createElement('a',{href:typeof href==='string'?href:href.pathname,...rest},children)};if(request==='next/navigation')return {usePathname:()=>'/test',notFound(){throw new Error('NOT_FOUND')}};if(request==='@/db')return {getDb(){return {insert(){return {async values(v){if(failDb)throw Error('Unavailable');records.push(v)}}}}}};if(request==='@/lib/zoho-leads')return {sendEnquiryToZoho:async()=>true};if(request==='@/db/schema')return {enquiries:{}};
 if(request.startsWith('@/')){const file=resolveLocal(path.join(root,request.slice(2)));if(file)return loadFile(file)}if(parent&&request.startsWith('.')){const file=resolveLocal(path.resolve(path.dirname(parent.filename),request));if(file&&/\.tsx?$/.test(file))return loadFile(file)}return originalLoad.apply(this,arguments)};
(async()=>{
 const {motionThemes}=loadFile(path.join(root,'lib/animated-assets.ts'));for(const theme of motionThemes){for(const ext of ['gif','webp'])assert(fs.existsSync(path.join(root,'public/animations',theme+'.'+ext)),'Missing animation '+theme);assert(fs.statSync(path.join(root,'public/animations',theme+'.gif')).size<100000,'Heavy animation '+theme);}
 const {services,industries}=loadFile(path.join(root,'lib/content.ts'));const {markets}=loadFile(path.join(root,'lib/markets.ts'));const {articles}=loadFile(path.join(root,'lib/articles.ts'));
 assert.equal(services.length,18);assert.equal(industries.length,12);assert.equal(markets.length,27);
 const {marketTranslations}=loadFile(path.join(root,'lib/market-locales.ts'));
 const routes=new Set(['/','/services','/performance-marketing','/organic-marketing','/industries','/markets','/packages','/blog','/contact','/about','/privacy','/dmb-audit','/seo-bureau','/ppc-bureau','/smm-bureau','/tools','/tools/seo-audit','/tools/ads-audit','/tools/social-media-audit',...services.map(s=>'/services/'+s.slug),...industries.map(i=>'/industries/'+i.slug),...markets.map(m=>'/markets/'+m.slug),...articles.map(a=>'/blog/'+a.slug),...marketTranslations.map(p=>'/markets/'+p.slug+'/'+p.language)]);
 const tasks=[];for(const route of ['/','/services','/performance-marketing','/organic-marketing','/industries','/markets','/packages','/blog','/contact','/about','/privacy','/dmb-audit','/seo-bureau','/ppc-bureau','/smm-bureau','/tools','/tools/seo-audit','/tools/ads-audit','/tools/social-media-audit'])tasks.push({route,file:path.join(root,'app',route==='/'?'page.tsx':route.slice(1)+'/page.tsx')});
 for(const [type,items] of [['services',services],['industries',industries],['markets',markets],['blog',articles]])for(const item of items)tasks.push({route:'/'+type+'/'+item.slug,file:path.join(root,'app',type,'[slug]','page.tsx'),slug:item.slug});
 // Character counts are editorial warnings, not hard search-engine validity limits.
 const titles=new Set();const descriptions=new Set();const titleLengthWarnings=[];let linkCount=0;const shell=loadFile(path.join(root,'app/layout.tsx').replace('layout.tsx','../components/site-shell.tsx'));
 for(const t of tasks){const mod=loadFile(t.file);const props=t.slug?{params:Promise.resolve({slug:t.slug})}:{};const meta=t.slug?await mod.generateMetadata(props):mod.metadata;assert(meta.description,`Description missing ${t.route}`);assert(meta.description.length<=160,`Long description ${t.route}`);assert(meta.alternates?.canonical.endsWith(t.route==='/'?'/':t.route),`Canonical mismatch ${t.route}`);const title=typeof meta.title==='string'?meta.title:meta.title.absolute;assert(title.length>0,`Empty title ${t.route}`);if(title.length>65)titleLengthWarnings.push(t.route);assert(!titles.has(title),`Duplicate title ${title}`);assert(!descriptions.has(meta.description),`Duplicate description ${t.route}`);titles.add(title);descriptions.add(meta.description);const tree=await mod.default(props);const html=renderToStaticMarkup(React.createElement(React.Fragment,null,React.createElement(shell.Header),tree,React.createElement(shell.Footer)));assert.equal((html.match(/<h1[\s>]/g)||[]).length,1,`H1 ${t.route}`);assert(html.includes('id="main"'));if(t.route!=='/'){const schemas=Array.from(html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g),m=>JSON.parse(m[1]));const breadcrumbs=schemas.filter(s=>s['@type']==='BreadcrumbList');assert.equal(breadcrumbs.length,1,'Breadcrumb schema count '+t.route);breadcrumbs[0].itemListElement.forEach((item,index,list)=>{assert.equal(item.position,index+1);assert(item.name);if(index<list.length-1)assert(/^https:\/\/dmbureau.cloud(?:\/|$)/.test(item.item),'Breadcrumb absolute URL '+t.route)});}assert(!/amp-boilerplate|cdn\.ampproject|rel="amphtml"/.test(html),`Unexpected AMP signal ${t.route}`);for(const img of html.matchAll(/<img[^>]+src="(\/[^"]+)"/g)){assert(fs.existsSync(path.join(root,'public',img[1])),`Missing image ${t.route} -> ${img[1]}`)}for(const match of html.matchAll(/href="(\/[^"]*)"/g)){const dest=match[1].split('?')[0].split('#')[0];assert(routes.has(dest)||require('fs').existsSync(path.join(root,'public',dest)),`Broken internal link ${t.route} -> ${dest}`);linkCount++}}
 for(const type of ['services','industries','markets','blog']){const mod=loadFile(path.join(root,'app',type,'[slug]','page.tsx'));await assert.rejects(()=>mod.default({params:Promise.resolve({slug:'not-a-real-route'})}),/NOT_FOUND/)}
 const api=loadFile(path.join(root,'app/api/enquiries/route.ts'));const valid={name:'Test Buyer',email:'buyer@example.test',company:'Test business',website:'https://example.test',market:'Dubai',industry:'real-estate',service:'google-ads-management',package:'diagnosis',budget:'Not decided',problem:'We receive clicks but no qualified property enquiries.',consent:'yes',fax:''};
 const req=(payload,origin='https://dmb.test')=>new Request('https://dmb.test/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify(payload)});
 const ok=await api.POST(req(valid));assert.equal(ok.status,201);const result=await ok.json();assert(/^DMB-[A-F0-9]{8}$/.test(result.reference));assert.equal(records.length,1);assert.equal(records[0].market,'Dubai');assert.equal(records[0].service,'google-ads-management');
 const briefOnly=await api.POST(req({name:'Test Buyer',email:'buyer@example.test',problem:'We need help getting suitable enquiries.',consent:'yes'}));assert.equal(briefOnly.status,201);assert.equal(records[1].company,'');assert.equal(records[1].market,'Multiple markets');
 for(const market of markets){assert.equal((await api.POST(req({...valid,market:market.name}))).status,201,'Country form rejected '+market.name);}
 const budgetTools=loadFile(path.join(root,'lib/enquiry-budget.ts'));for(const [market,currency] of [['India','INR'],['United Kingdom','GBP'],['Dubai','AED'],['UAE','AED'],['Kuwait','KWD'],['United States','USD']]){assert.equal(budgetTools.enquiryCurrency(market),currency);assert(budgetTools.enquiryBudgetOptions(currency).slice(1).every(v=>v.endsWith(currency)));}
 
 for(const bad of [{...valid,consent:''},{...valid,email:'bad'},{...valid,problem:'short'},{...valid,service:'unknown'},{...valid,market:'fake'},{...valid,website:'javascript:alert(1)'},{...valid,fax:'spam'}])assert.equal((await api.POST(req(bad))).status,400);
 assert.equal((await api.POST(req(valid,'https://evil.test'))).status,403);assert.equal((await api.POST(new Request('https://dmb.test/api/enquiries',{method:'POST',body:'{bad'}))).status,400);assert.equal((await api.POST(req({...valid,problem:'x'.repeat(20000)}))).status,413);failDb=true;assert.equal((await api.POST(req(valid))).status,503);
 const map=await loadFile(path.join(root,'app/sitemap.xml/route.ts')).GET();const xml=await map.text();const count=(xml.match(/<loc>/g)||[]).length;assert.equal(count,91);assert(!xml.includes('/packages'));for(const match of xml.matchAll(/<loc>[^<]*chatgpt\.site([^<]*)<\/loc>/g))assert(routes.has(match[1]||'/'));
 const robots=await loadFile(path.join(root,'app/robots.txt/route.ts')).GET();assert((await robots.text()).includes('Disallow: /api/'));
 console.log(JSON.stringify({pagesRendered:tasks.length,internalLinksChecked:linkCount,uniqueTitles:titles.size,uniqueDescriptions:descriptions.size,titleLengthWarnings:titleLengthWarnings.length,sitemapUrls:count,invalidRoutesChecked:4,enquiryValidationCases:12,storageContract:'valid requests persist; failure returns error; no success on failed storage'},null,2));
})().catch(e=>{console.error(e);process.exit(1)});
