const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript'),assert=require('node:assert/strict');const root=process.cwd();const cache=new Map();const old=Module._load;
function load(file){if(cache.has(file))return cache.get(file).exports;const m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));cache.set(file,m);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);return m.exports}
Module._load=function(req,parent){if(req.startsWith('@/'))return load(path.join(root,req.slice(2)+'.ts'));return old.apply(this,arguments)};
(async()=>{const a=load(path.join(root,'lib/audit.ts'));const html=`<html lang="en"><head><title>Example service</title><meta name="description" content="A useful service"><meta name="viewport" content="width=device-width,initial-scale=1"><meta property="og:title" content="Example"><meta property="og:description" content="Useful"><link rel="canonical" href="https://example.com/"><script type="application/ld+json">{"@context":"https://schema.org","@type":"Organization"}</script></head><body><h1>Example service</h1><img src="x" alt=""><p>${'useful '.repeat(110)}</p></body></html>`;const full=a.analysePage(html,'https://example.com/');assert.equal(full.passed,11);assert.equal(full.score,100);const empty=a.analysePage('<html><h1>One</h1><h1>Two</h1><img src="x"></html>','http://example.com/');assert.equal(empty.checks.find(x=>x.id==='alt').passed,false);assert.equal(empty.checks.find(x=>x.id==='h1').passed,false);assert.equal(empty.checks.find(x=>x.id==='https').passed,false);assert.equal(a.validatePublicUrl('example.com').href,'https://example.com/');
for(const u of ['http://localhost','http://127.0.0.1','http://[::1]','http://192.168.0.1','https://user:pass@example.com','https://example.com:444','https://foo.local','https://metadata.google.internal','file:///etc/passwd'])assert.throws(()=>a.validatePublicUrl(u));for(const ip of ['127.0.0.1','10.0.0.1','172.16.0.1','169.254.169.254','192.168.0.1','::1','::ffff:127.0.0.1','fd00::1','fe80::1'])assert.equal(a.isPublicAddress(ip),false);assert(a.isPublicAddress('93.184.216.34'));assert(a.isPublicAddress('2606:4700:4700::1111'));
const api=load(path.join(root,'app/api/audit/route.ts'));const request=(url,origin='https://dmb.test')=>new Request('https://dmb.test/api/audit',{method:'POST',headers:{origin},body:JSON.stringify({url})});let mode='normal';let siteFetches=0;const originalFetch=global.fetch;
global.fetch=async url=>{if(String(url).startsWith('https://cloudflare-dns.com'))return Response.json({Answer:String(url).includes('type=AAAA')?[]:[{type:1,data:mode==='private'?'127.0.0.1':'93.184.216.34'}]});siteFetches++;if(mode==='blocked')return new Response('Forbidden',{status:403});if(mode==='redirect')return new Response('',{status:302,headers:{location:'http://127.0.0.1/private'}});if(mode==='file')return new Response('binary',{headers:{'content-type':'application/pdf'}});if(mode==='large')return new Response('x'.repeat(1500001),{headers:{'content-type':'text/html'}});return new Response(html,{headers:{'content-type':'text/html'}})};
try{const good=await api.POST(request('example.com'));assert.equal(good.status,200);assert.equal((await good.json()).score,100);assert.equal((await api.POST(request('localhost'))).status,400);assert.equal((await api.POST(request('example.com','https://evil.test'))).status,403);mode='private';const before=siteFetches;assert.equal((await api.POST(request('example.com'))).status,422);assert.equal(siteFetches,before);for(const m of ['blocked','redirect','file','large']){mode=m;assert.equal((await api.POST(request('example.com'))).status,422)}assert.equal((await api.POST(new Request('https://dmb.test/api/audit',{method:'POST',body:'{bad'}))).status,422)}finally{global.fetch=originalFetch}
console.log(JSON.stringify({auditChecks:11,validHTML:'passed',missingMetadata:'passed',URLAndPrivateAddressGuards:'passed',DNSRedirectAndSizeGuards:'passed',upstreamFailureHandling:'passed',verification:'fixture and server contract checks; not a hosted network test'},null,2))})().catch(e=>{console.error(e);process.exit(1)});
