import { env } from 'cloudflare:workers';
import { validatePublicUrl,isPublicAddress } from '@/lib/audit';
import { readLighthouse,readCrux } from '@/lib/audit-performance';
export async function POST(request:Request){const headers={'Cache-Control':'private, no-store'};if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Use the website audit form.'},{status:403,headers});try{const raw=await request.text();if(raw.length>2500)throw Error('Request is too large.');const data=JSON.parse(raw);const url=validatePublicUrl(typeof data?.url==='string'?data.url:'');const strategy=data.strategy==='desktop'?'desktop':'mobile';const signal=AbortSignal.timeout(55000);const dns=await Promise.all(['A','AAAA'].map(async type=>{const r=await fetch('https://cloudflare-dns.com/dns-query?name='+encodeURIComponent(url.hostname)+'&type='+type,{headers:{Accept:'application/dns-json'},signal});if(!r.ok)throw Error('The domain could not be checked.');const d=await r.json() as any;return (d.Answer||[]).filter((a:any)=>a.type===1||a.type===28).map((a:any)=>a.data as string)}));if(!dns.flat().length||dns.flat().some(ip=>!isPublicAddress(ip)))throw Error('Use a publicly reachable website.');
const bindings=env as unknown as {PAGESPEED_API_KEY?:string;CRUX_API_KEY?:string};const endpoint=new URL('https://www.googleapis.com/pagespeedonline/v5/runPagespeed');endpoint.searchParams.set('url',url.toString());endpoint.searchParams.set('strategy',strategy);for(const category of ['performance','accessibility','best-practices','seo'])endpoint.searchParams.append('category',category);if(bindings.PAGESPEED_API_KEY)endpoint.searchParams.set('key',bindings.PAGESPEED_API_KEY);
const labTask=fetch(endpoint,{signal}).then(async r=>{
 if(!r.ok)return {lab:null,message:r.status===429?'Google PageSpeed quota is temporarily exhausted (HTTP 429). Retry this device later.':r.status===401||r.status===403?'Google PageSpeed denied access (HTTP '+r.status+'). Check the API key and enabled API.':'Google PageSpeed could not run this test (HTTP '+r.status+'). Retry this device.'};
 const lab=readLighthouse(await r.json());return {lab,message:lab?undefined:'Google Lighthouse could not complete the page-load test. Check the page in Google PageSpeed and retry.'};
}).catch((e)=>({lab:null,message:e instanceof Error&&e.name==='TimeoutError'?'Google PageSpeed timed out. Retry this device.':'Google PageSpeed could not be reached. Retry this device.'}));
const fieldTask=(async()=>{
 const unavailable=(message:string)=>({status:'unavailable' as const,lcp:null,inp:null,cls:null,message});
 if(!bindings.CRUX_API_KEY)return unavailable('Chrome UX Report is not connected. A CrUX API key is required for real-user metrics.');
 for(const scope of ['page','origin'] as const){
  const r=await fetch('https://chromeuxreport.googleapis.com/v1/records:queryRecord?key='+encodeURIComponent(bindings.CRUX_API_KEY),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...scope==='page'?{url:url.toString()}:{origin:url.origin},formFactor:strategy==='mobile'?'PHONE':'DESKTOP',metrics:['largest_contentful_paint','interaction_to_next_paint','cumulative_layout_shift']}),signal});
  if(r.ok){const result=readCrux(await r.json(),scope);if(result)return result;return unavailable('Google returned no usable real-user metrics for this device.');}
  if(r.status===404)continue;
  if(r.status===401||r.status===403)return unavailable('Google denied Chrome UX Report access (HTTP '+r.status+'). Check that the API is enabled and the server key allows Chrome UX Report requests.');
  if(r.status===429)return unavailable('Chrome UX Report quota is temporarily exhausted (HTTP 429). Retry later.');
  return unavailable('Chrome UX Report could not return data (HTTP '+r.status+'). Retry later.');
 }
 return unavailable('Google has no Chrome UX Report record for this page or website origin on '+strategy+'. There may not be enough eligible real-user visits.');
})().catch((e)=>({status:'unavailable' as const,lcp:null,inp:null,cls:null,message:e instanceof Error&&e.name==='TimeoutError'?'Chrome UX Report timed out. Retry this device.':'Chrome UX Report could not be reached. Retry this device.'}));const [labResult,field]=await Promise.all([labTask,fieldTask]);const lab=labResult.lab;return Response.json({status:lab?'ready':'unavailable',strategy,checkedAt:new Date().toISOString(),lab:lab||undefined,field,message:labResult.message},{headers});}catch(e){return Response.json({error:e instanceof Error&&e.name==='TimeoutError'?'The speed test timed out. Try again.':'The speed test could not run. Check the website address and try again.'},{status:422,headers})}}

