import styles from './audit.module.css';
import Link from '@/components/navigation-link';
import { Breadcrumb, Schema, CTA } from '@/components/blocks';
import { HeroAudit } from '@/components/hero-audit';
import { pageMeta, origin } from '@/lib/site';
export const metadata=pageMeta('Free SEO, Social Media & Ads Readiness Audit','Audit your website SEO, social links, ads readiness and conversion signals. Explore an evidence-based report with scores, details and priority fixes.','/free-seo-audit');
const faqs=[
 {q:'Can I download the report?',a:'The online report is free to review. Paid report downloads are being configured; checkout is not active yet and no payment is taken.'},
 {q:'Can a URL reveal my ads and social media performance?',a:'No. A URL can show linked profiles, sharing metadata and some tracking signals. Spend, ROAS, campaign targeting, audience insights, reach and engagement require authorized account data. Missing markers are shown as not observed, not as proof that your accounts are inactive.'},
 {q:'What does the marketing audit check?',a:'The initial report examines SEO metadata, headings, discovery files, social profile links, sharing previews, advertising tracking markers and contact paths on the submitted page. You can then run the separate URL crawl to check discovered pages for HTTP errors and possible soft 404s.'},
 {q:'Does it check every page automatically?',a:'The initial check covers your submitted URL. The URL crawl discovers same-origin pages from sitemaps and links. It processes up to 2,000 documents per run, with a discovery queue capped at 20,000. Continue the crawl while keeping the report open. Unlinked pages, excluded URLs and blocked content can remain unchecked.'},
 {q:'Can it measure mobile performance?',a:'The report can request Google PageSpeed Insights. Lab results describe a test run; real-user metrics depend on sufficient Chrome UX Report data. A missing result is shown as unavailable rather than scored as a failure.'},
 {q:'Are backlinks, traffic and competitor results included?',a:'Verified traffic, backlinks, advertiser records and business listing information need supported data providers. If a connection or a reliable match is unavailable, the report identifies that limitation. It does not invent these numbers.'},
 {q:'Will fixing the report guarantee rankings or AI citations?',a:'No. The report helps you prioritise observable website issues. Rankings and AI answers also depend on useful content, competition and the systems that select results.'}
];
export default function FreeAudit(){return <main id="main"><section className={'page-intro '+styles.toolIntro}><Breadcrumb items={[{label:'Marketing audit'}]}/><span className="eyebrow">Your website, checked</span><h1>Free Website Marketing Audit</h1><p>One URL to review your SEO, social presence signals, advertising readiness and conversion paths. Get a clear report with evidence and practical next steps.</p><HeroAudit fullPage/></section><section className="section"><div className="section-heading"><div><span className="eyebrow">What the report covers</span><h2>Turn findings into a clear improvement plan.</h2></div></div><div className="process-grid">{[
 ['01','On-page SEO','Review titles, descriptions, headings and canonical signals on the submitted page.'],
 ['02','Discovery and URL health','Check sitemap, robots.txt and llms.txt availability, then crawl discoverable URLs for 404, 5xx and possible soft 404 issues.'],
 ['03','Social media readiness','Discover linked social profiles and sharing metadata. Profile ownership, engagement and reach need platform data.'],
 ['04','Ads readiness','Review tracking markers, contact destinations and privacy links. Campaign spend, targeting and ROAS need authorized ad-account access.'],
 ['05','Conversion signals','Check public contact paths and page usability. Form delivery, lead quality and sales outcomes require further testing.'],
 ['06','Performance and next steps','Request available performance evidence and prioritize fixes. Unavailable or blocked checks stay separate from confirmed problems.']
 ].map(([n,t,d])=><div className="process-card" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section><section className="section" id="methodology"><span className="eyebrow">Audit methodology</span><h2>Evidence first. Clear limits.</h2><div className="article-body"><p>The tool requests public website content and reports the signals it can observe. Colour labels distinguish passing checks, issues, recommendations and unavailable evidence; they are diagnostic guidance, not a Google ranking score.</p><p>A successful HTTP response alone does not prove a sitemap is valid, a page is indexed or a bot can access every URL. Soft 404 findings are heuristic and should be reviewed before changing a page.</p><p>External data checks depend on configured providers, their coverage and a reliable business match. AI recommendations, when available, interpret collected evidence and require human review. They cannot establish search volume, backlinks or competitor rankings without source data.</p><p>Review the checked URL, observation time and crawl coverage before acting. Re-run relevant checks after changes. See our <Link href="/privacy">privacy notice</Link> for how website inputs and enquiry information are handled.</p></div></section><section className="section"><span className="eyebrow">Common questions</span><h2>Understand your marketing audit.</h2><div className={styles.questions}>{faqs.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</div></section><CTA title="Need help implementing the findings?" text="Share your report and business goal. We can agree a focused scope for the work."/><Schema data={{'@context':'https://schema.org','@type':'WebPage','@id':origin+'/free-seo-audit#webpage',url:origin+'/free-seo-audit',name:'Website Marketing Audit Report',description:'A website marketing audit covering public SEO, SMM, ads readiness and conversion signals with transparent coverage limits.',isPartOf:{'@id':origin+'/#website'},publisher:{'@id':origin+'/#organization'}}}/><Schema data={{'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:f.a}}))}}/></main>}
