import {ThemeHero} from '@/components/theme-sections';
import {AnimatedHeading} from '@/components/animated-heading';
import {ServiceVisual} from '@/components/service-visual';
import Link from '@/components/navigation-link';
import { notFound } from 'next/navigation';
import { articles } from '@/lib/articles';
import { services } from '@/lib/content';
import { Breadcrumb, CTA, SectionTitle, ServiceCard, Schema } from '@/components/blocks';
import { pageMeta, origin } from '@/lib/site';
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(a=>a.slug===slug);return a?pageMeta(({ 'clicks-but-no-leads':'Google Ads Clicks but No Leads: What to Check','traffic-but-no-enquiries':'Website Traffic but No Enquiries: Conversion Guide','measure-qualified-leads':'How to Measure Lead Quality','international-service-pages':'International SEO for Service Businesses'} as Record<string,string>)[a.slug]||a.title,a.summary,'/blog/'+slug):{title:'Insight not found'}}
export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(a=>a.slug===slug);if(!a)notFound();return <main id="main" className="theme-interior-page"><ThemeHero title={<>{a.title}</>} trail={[{label:'Blog',href:'/blog'},{label:a.title}]} kicker={<>{a.category} / {a.read} read</>} description={<>{a.summary}</>} visual={<ServiceVisual featureKey={"article-"+slug} slug={slug.includes("clicks")?"google-ads-management":slug.includes("traffic")?"conversion-optimization":slug.includes("qualified")?"conversion-optimization":"seo-bureau"}/>} extra={<><div className="article-byline"><Link href="/about#editorial-process">Digital Marketing Bureau editorial team</Link> · Updated 7 October 2026</div></>}/><div className="theme-reading-layout"><aside className="theme-reading-nav"><span className="eyebrow">In this guide</span><nav aria-label="Article sections">{a.sections.map((s,n)=><a href={"#article-section-"+n} key={s.title}>{s.title}</a>)}</nav><Link className="button" href="/contact">Discuss your project</Link></aside><article className="article-body">{a.sections.map((s,n)=><section id={"article-section-"+n} key={s.title}><span className="eyebrow">0{n+1}</span><h2>{s.title}</h2><p>{s.body}</p></section>)}<div className="source-box"><span className="eyebrow">Further reading</span><a href={a.source.url} target="_blank" rel="noopener noreferrer">{a.source.label} ↗</a></div></article></div><section className="section related-section"><SectionTitle kicker="Turn the diagnosis into action" title="Explore the relevant services."/><div className="service-grid">{a.related.map(sl=>services.find(s=>s.slug===sl)).map(s=><ServiceCard service={s!} key={s!.slug}/>)}</div></section><CTA/><Schema data={{'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.summary,mainEntityOfPage:origin+'/blog/'+slug,author:{'@type':'Organization',name:'Digital Marketing Bureau editorial team',url:origin+'/about#editorial-process'},publisher:{'@id':origin+'/#organization'},dateModified:'2026-10-07',about:a.category}}/></main>}

