import {ThemeHero} from '@/components/theme-sections';
import Link from '@/components/navigation-link';
import {auditTools} from '@/lib/audit-tools';
import {AnimatedHeading} from '@/components/animated-heading';
import {HeroAudit} from '@/components/hero-audit';
import {Schema,Breadcrumb} from '@/components/blocks';
import {pageMeta,origin} from '@/lib/site';
import styles from './audit.module.css';
export const metadata=pageMeta('DMB Audit Tool | SEO, Social Media & Ads Readiness','Run DMB Audit to check your website SEO, social links, ads readiness and conversion signals. See scores, evidence and priority fixes in one report.','/dmb-audit');
export default function DMBAudit(){return <main id="main" className={styles.workspace}><ThemeHero title={<><span>Website Audit</span> &amp; Reporting Tool</>} kicker="DMB AUDIT" description="SEO + Social Media + Ads Readiness. One website. A detailed report of what works, what needs attention and what to fix first." trail={[{label:"DMB Audit"}]}/><section className={styles.tool+" theme-audit-workbench"}><div className={styles.focusTools}>{auditTools.map(t=><Link href={t.href} key={t.kind}>{t.name} →</Link>)}</div><HeroAudit fullPage/><details id="methodology" className={styles.coverage}><summary>What can DMB Audit check?</summary><p>The initial scan reviews the submitted page, public SEO signals, discovery files, linked social profiles, sharing previews, tracking markers and contact paths. Mobile and desktop performance checks start separately after the report loads. A full URL crawl can be started from the report.</p><p>Social engagement, ad spend, ROAS and campaign targeting require authorized account data. Missing data stays clearly labeled. Online results are free to view; paid downloads are not active until checkout is configured.</p></details></section><Schema data={{'@context':'https://schema.org','@type':'WebPage','@id':origin+'/dmb-audit#webpage',url:origin+'/dmb-audit',name:'DMB Audit Tool',description:'Website marketing audit covering SEO, social media signals, ads readiness and conversion paths.',isPartOf:{'@id':origin+'/#website'},publisher:{'@id':origin+'/#organization'}}}/></main>}
